### ISSUE TITLE
Microsoft.Extensions.Caching.StackExchangeRedis SetString BUG

### ISSUE THREAD

**Issue by dashiell-zhang** [microsoft/garnet#121]
<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.3" />

My project uses Microsoft.Extensions.Caching.StackExchangeRedis as the implementation of distributed cache. When connected to Garnet, the Set action will return an ERR unknown command exception.

IDistributedCache distributedCache

distributedCache.SetString(key, value, new DistributedCacheEntryOptions { AbsoluteExpirationRelativeToNow = absoluteExpirationRelativeToNow });

ERR unknown command

**Comment by yzy613** [comment]
Currently, garnet does not fully support all redis commands.

**Comment by douglasg14b** [comment]
What commands are unsupported for this scenario?

**Comment by davidglassborow** [comment]
See https://github.com/microsoft/garnet/issues/85

**Comment by yzy613** [comment]
> What commands are unsupported for this scenario?

You can see [api-compatibility](https://microsoft.github.io/garnet/docs/commands/api-compatibility).

**Comment by badrishc** [comment]
Can you provide a simple repro - it should be possible to detect what variant of SET is being sent and add that relatively easily.

**Comment by badrishc** [comment]
Or, just run the Garnet server in Debug mode with these three lines uncommented and with --logger-level Trace, then it will tell you what was received and unable to handle:

https://github.com/microsoft/garnet/blob/main/libs/server/Resp/RespServerSession.cs#L241

**Comment by davidglassborow** [comment]
All the details are on #85 

- The Redis IDistributedCache implementation depends on Lua
- It doesn't need to, the area owner has raised an issue and PR https://github.com/dotnet/aspnetcore/issues/54685

**Comment by badrishc** [comment]
Closing as the error will resolve once the above PR eliminating Lua merges.
