### ISSUE TITLE
Is there a plan to release the docker image in DockerHub?

### ISSUE THREAD

**Issue by itsmuntadhar** [microsoft/garnet#122]
Would like to know if there're plans to release the Docker image in DockerHub?

**Comment by yzy613** [comment]
***I'm not an official developer.***

I guess they have no plans to release images on Dockers Hub in the short term. But I continue to maintain _an unofficial image repository_[^1], and you can also easily pull the image to use.

[^1]: yzy613/garnet

### Quick Start

```shell
docker run -d \
    -p 3278:3278 \
    yzy613/garnet:latest
```

**Comment by douglasg14b** [comment]
Related to #34

**Comment by darrenge** [comment]
We now have packages here: https://github.com/microsoft/garnet/pkgs/container/garnet   We plan to add any future containers in this place too. As for putting out containers in Docker Hub or Microsoft Artifact Registry is TBD.

**Comment by itsmuntadhar** [comment]
thanks, closing due to being answered
