### ISSUE TITLE
Was the wiki meant to be enabed?

### ISSUE THREAD

**Issue by douglasg14b** [microsoft/garnet#124]
Noticed it was enabled: 
![image](https://github.com/microsoft/garnet/assets/1400380/c6390167-01c3-4e05-8b5a-a782dbcc9582)

There's the docosaurus docs, and the wiki. Is there an objective for the wiki, or just leftover?

**Comment by badrishc** [comment]
It makes sense to get rid of it given we have all the other sources of information. I have removed it.
