### ISSUE TITLE
redis-benchmark throws a System.NullReferenceException

### ISSUE THREAD

**Issue by shyim** [microsoft/garnet#129]
I did run just `redis-benchmark -p 3278` after few seconds errors like

```
07::14::50 crit: Session[0] [192.168.50.212:3278] [127.0.0.1:60714] [0170180D] ProcessMessages threw exception System.NullReferenceException: Object reference not set to an instance of an object.    at Garnet.server.StorageSession.RMWObjectStoreOperation[TObjectContext](Byte[] key, ArgSlice input, ObjectOutputHeader& output, TObjectContext& objectStoreContext) in /build/source/libs/server/Storage/Session/ObjectStore/Common.cs:line 25    at Garnet.server.StorageSession.ListPush[TObjectContext](Byte[] key, ArgSlice input, ObjectOutputHeader& output, TObjectContext& objectStoreContext) in /build/source/libs/server/Storage/Session/ObjectStore/ListOps.cs:line 321    at Garnet.server.GarnetApi`2.ListLeftPush(Byte[] key, ArgSlice input, ObjectOutputHeader& output) in /build/source/libs/server/API/GarnetApiObjectCommands.cs:line 171    at Garnet.server.RespServerSession.ListPush[TGarnetApi](Int32 count, Byte* ptr, ListOperation lop, TGarnetApi& storageApi) in /build/source/libs/server/Resp/Objects/ListCommands.cs:line 75    at Garnet.server.RespServerSession.ProcessArrayCommands[TGarnetApi](TGarnetApi& storageApi) in /build/source/libs/server/Resp/RespServerSession.cs:line 458    at Garnet.server.RespServerSession.ProcessBasicCommands[TGarnetApi](Byte* ptr, RespCommand cmd, TGarnetApi& storageApi) in /build/source/libs/server/Resp/RespServerSession.cs:line 327    at Garnet.server.RespServerSession.ProcessMessages() in /build/source/libs/server/Resp/RespServerSession.cs:line 273    at Garnet.server.RespServerSession.TryConsumeMessages(Byte* reqBuffer, Int32 bytesReceived) in /build/source/libs/server/Resp/RespServerSession.cs:line 199
```

popped up. Running several times `redis-benchmark` does not work as the client disconnects with: `Error: Server closed the connection`

**Comment by vazois** [comment]
We fixed the issue with SPOP. The redis benchmark should run correctly now, with the exception of XADD which is not currently supported. Let us know if you are having any more issues.

**Comment by springmin** [comment]
run "redis-benchmark -p 3278 -n 1000000  -q" show Error: Server closed the connection after running show detail:
PING_INLINE: 15564.44 requests per second, p50=1.511 msec
PING_MBULK: 15175.43 requests per second, p50=1.543 msec
SET: 15701.79 requests per second, p50=1.495 msec
GET: 15750.51 requests per second, p50=1.503 msec
INCR: 15199.88 requests per second, p50=1.543 msec
Error: Server closed the connection

the server  show this error info :
03::33::39 crit: Session[0] [10.68.10.104:3278] [127.0.0.1:63426] [0070BEE3] ProcessMessages threw exception System.NullReferenceException: Object reference not set to an instance of an object.    at Garnet.server.StorageSession.RMWObjectStoreOperation[TObjectContext](Byte[] key, ArgSlice input, ObjectOutputHeader& output, TObjectContext& objectStoreContext) in D:\springmin\GitHub\microsoft\garnet\libs\server\Storage\Session\ObjectStore\Common.cs:line 25    at Garnet.server.StorageSession.ListPush[TObjectContext](Byte[] key, ArgSlice input, ObjectOutputHeader& output, TObjectContext& objectStoreContext) in D:\springmin\GitHub\microsoft\garnet\libs\server\Storage\Session\ObjectStore\ListOps.cs:line 321    at Garnet.server.GarnetApi`2.ListLeftPush(Byte[] key, ArgSlice input, ObjectOutputHeader& output) in D:\springmin\GitHub\microsoft\garnet\libs\server\API\GarnetApiObjectCommands.cs:line 171    at Garnet.server.RespServerSession.ListPush[TGarnetApi](Int32 count, Byte* ptr, ListOperation lop, TGarnetApi& storageApi) in D:\springmin\GitHub\microsoft\garnet\libs\server\Resp\Objects\ListCommands.cs:line 75    at Garnet.server.RespServerSession.ProcessArrayCommands[TGarnetApi](TGarnetApi& storageApi) in D:\springmin\GitHub\microsoft\garnet\libs\server\Resp\RespServerSession.cs:line 376    at Garnet.server.RespServerSession.ProcessBasicCommands[TGarnetApi](Byte* ptr, RespCommand cmd, TGarnetApi& storageApi) in D:\springmin\GitHub\microsoft\garnet\libs\server\Resp\RespServerSession.cs:line 327    at Garnet.server.RespServerSession.ProcessMessages() in D:\springmin\GitHub\microsoft\garnet\libs\server\Resp\RespServerSession.cs:line 273    at Garnet.server.RespServerSession.TryConsumeMessages(Byte* reqBuffer, Int32 bytesReceived) in D:\springmin\GitHub\microsoft\garnet\libs\server\Resp\RespServerSession.cs:line 199

**Comment by hez2010** [comment]
you can pull the latest code from the main branch. this issue should no longer happen in the latest code.

**Comment by springmin** [comment]
thanks，the issue is fixed。
