### ISSUE TITLE
Kubernetes operator ?

### ISSUE THREAD

**Issue by 16pierre** [microsoft/garnet#141]
Thanks for open-sourcing this project, this is awesome news, tempted to give it a shot.

Is there any plan to open-source a Kubernetes operator / utils to ease the deployment of Garnet, especially in cluster mode ?

**Comment by darrenge** [comment]
We now have container packages here: https://github.com/microsoft/garnet/pkgs/container/garnet   Any future containers will be put in this place too but what we put here is TBD. As for putting out containers in Docker Hub or Microsoft Artifact Registry is also TBD.

**Comment by badrishc** [comment]
More information is also available here: https://microsoft.github.io/garnet/docs/welcome/releases
