### ISSUE TITLE
Memory Usage Growth when using KEYS * command

### ISSUE THREAD

**Issue by cduluCNB** [microsoft/garnet#143]
I understand that this is an edge case and it's not recommended to do this generally, however I noticed that there's significant memory usage growth when running KEYS * multiple times in a row, even if the cache is empty. 

I'm able to reproduce in version 1.0.1, compiled in VS2022 in Release/Any CPU mode and using the .NET 8 version.

I then use the memurai-cli client and type KEYS * a few times. The memory usage will grow way beyond the memory limits that I've set in my garnet.conf file (see attached).

I've narrowed it down to TsavoriteBase.cs line 113 - whenever it calls **internal void Initialize(int version, long size, int sector_size)** it's calling it twice, allocating ~500MB memory each time, so each time I call KEYS *, memory grows by ~1.1GB.

However, I do notice that if I do this enough times, the GC will eventually free the memory so that's not too bad. 

Just wondering if there's any way to restrict the amount of memory being allocated? Or even why the KEYS command needs to allocate that much memory in the first place. It also seems like the allocator is ignoring all of the memory settings (I tried MemorySize, IndexSize, IndexMaxSize, ObjectStoreTotalMemorySize settings to no avail). 

Not sure what the fix would be, if there even needs to be one.

Thanks in advance,

Config file:
[garnet.conf.txt](https://github.com/microsoft/garnet/files/14761561/garnet.conf.txt)

Line 113 where it allocates ~500MB:
![2024-03-26 08_50_45-Garnet (Debugging) - Microsoft Visual Studio Preview (Administrator)](https://github.com/microsoft/garnet/assets/147778626/c9694882-8292-4396-9156-ec7a2bbcaf46)

Memory Usage
![2024-03-26 08_33_01-Task Manager](https://github.com/microsoft/garnet/assets/147778626/1b87620c-2542-49fc-b41b-a18f04a83762)

**Comment by TedHartMS** [comment]
The paired calls to Initialize are due to the main store and object store. This line is allocating the hash table, and when called from TsavoriteKVIterator ctor, it's for a temporary TsavoriteKV used as a lookup table to build up the set of keys. This tempKV uses store.IndexSize, so can you double-check whether this is the value you specified for that?

**Comment by cduluCNB** [comment]
> The paired calls to Initialize are due to the main store and object store. This line is allocating the hash table, and when called from TsavoriteKVIterator ctor, it's for a temporary TsavoriteKV used as a lookup table to build up the set of keys. This tempKV uses store.IndexSize, so can you double-check whether this is the value you specified for that?

Hi Ted,

Ahh so it's a temporary lookup table to build the set of keys. My IndexSize is 512mb so it lines up with the memory growth. However, does it need to allocate a new hash table each time KEYS is called? This might be a stupid question, but can the hash table be cleared and then reused if it's already been allocated previously? Or conversely, is my IndexSize too big? My workload needs are super modest - we would only be using several thousands of objects at a time, and accessed a few hundreds of times per second during peak period. And we won't be using the KEYS command in production anyway.

Thanks,
Christian

**Comment by badrishc** [comment]
When sizing index, a good rule of thumb would be to keep 16 bytes per key so that the index is half full. So for thousands of objects, you don't need a large index. Probably "1m" size is sufficient.

**Comment by cduluCNB** [comment]
> When sizing index, a good rule of thumb would be to keep 16 bytes per key so that the index is half full. So for thousands of objects, you don't need a large index. Probably "1m" size is sufficient.

Hi Badrish,

Thanks for your reply. 1m sounds great. If I follow your rule of thumb then 512mb is definitely overkill hahaha. 

With the following config values, my RAM usage maxes out around ~2GB before garbage collection, which is much more reasonable.

![2024-03-27 07_39_55-Garnet conf](https://github.com/microsoft/garnet/assets/147778626/9ddb110e-7944-41a8-8b43-fce84183a240)

**Comment by cduluCNB** [comment]
Should I close this issue then, or should I keep it open for further investigation, especially involving larger memory numbers?

**Comment by badrishc** [comment]
The behavior is by design, as we do need a temporary hash table to perform the iteration, in order to detect and eliminate duplicates. It is possible however to use a much smaller temporary hash table. If this is a problem in future, we can expose a separate setting so that users can employ a smaller temporary hash table.

**Comment by cduluCNB** [comment]
Fantastic, thank you! It's really not an issue then. I'll be closing this issue.

Thanks again.
