### ISSUE TITLE
SCAN command returns keys of expired objects

### ISSUE THREAD

**Issue by cduluCNB** [microsoft/garnet#151]
After setting an object and letting it expire, when running the SCAN command, Garnet still lists the key, while Redis does not.

This causes issues with RedisInsight and Another Redis Desktop Manager as they will run the TYPE command on each returned item from the SCAN command. The TYPE command bug is addressed in #150, however, even with this fix, in RedisInsight, the expired keys will show as having "No limit", and it'll show an error saying that the key with that name does not exist.

Using version 1.0.1, compiled in VS2022 in Release/Any CPU mode and using the .NET 8 version.

Garnet:
![2024-03-26 Garnet Scan](https://github.com/microsoft/garnet/assets/147778626/29fd8655-0d96-4599-a195-71e56f31807c)

Redis:
![2024-03-26 Redis Scan](https://github.com/microsoft/garnet/assets/147778626/053a82b6-1840-4ba6-a8a2-3e60808f58a3)

RedisInsight error:
![2024-03-26 RedisInsight Error](https://github.com/microsoft/garnet/assets/147778626/8ef42cd7-3245-4af9-ab7e-a2fef73c3c2b)

**Comment by cduluCNB** [comment]
My original tests were on Windows 11, using .NET 8.0.3 and VS 2022 Preview 17.10 Preview 1. I'm also able to replicate this using redis-cli with Garnet running on Ubuntu 22.04.3 LTS with .NET 8.0.3 in Release mode.

**Comment by ClericPy** [comment]
Encountered the same issue, any progress?

is it fixed by https://github.com/microsoft/garnet/pull/150 ?

**Comment by cduluCNB** [comment]
Hi @ClericPy this issue isn't fixed by #150, this is a different issue related to the SCAN command.

**Comment by ClericPy** [comment]
> Hi @ClericPy this issue isn't fixed by #150, this is a different issue related to the SCAN command.

So sorry I got a mistake, I used garnet 1.0 and expire not work. Used redispy & redis long time ago, and the code didn't changed. These days I noticed that the keys were not automatically purged according to their expire time when using db0

**Comment by cduluCNB** [comment]
> > Hi @ClericPy this issue isn't fixed by #150, this is a different issue related to the SCAN command.
> 
> So sorry I got a mistake, I used garnet 1.0 and expire not work. Used redispy & redis long time ago, and the code didn't changed. These days I noticed that the keys were not automatically purged according to their expire time when using db0

Yes, this is the same issue, keys aren't automatically purged in the list after their expiry time.

**Comment by ClericPy** [comment]
> > > Hi @ClericPy this issue isn't fixed by #150, this is a different issue related to the SCAN command.
> > 
> > 
> > So sorry I got a mistake, I used garnet 1.0 and expire not work. Used redispy & redis long time ago, and the code didn't changed. These days I noticed that the keys were not automatically purged according to their expire time when using db0
> 
> Yes, this is the same issue, keys aren't automatically purged in the list after their expiry time.

I don't know why this issue hasn't received much attention. Logically, there shouldn't be a shortage of users for this database, and the usage of TTL caching should be quite frequent.

**Comment by ClericPy** [comment]
> > > > Hi @ClericPy this issue isn't fixed by #150, this is a different issue related to the SCAN command.
> > > 
> > > 
> > > So sorry I got a mistake, I used garnet 1.0 and expire not work. Used redispy & redis long time ago, and the code didn't changed. These days I noticed that the keys were not automatically purged according to their expire time when using db0
> > 
> > 
> > Yes, this is the same issue, keys aren't automatically purged in the list after their expiry time.
> 
> I don't know why this issue hasn't received much attention. Logically, there shouldn't be a shortage of users for this database, and the usage of TTL caching should be quite frequent.

By the way, is there a temporary solution without experimentation that can solve the problem of having 30 million expired keys stored now:

scan all keys and manually determine expire and then manually clear them

**Comment by cduluCNB** [comment]
Hi @TedHardMs,

The issue has been fixed for strings, but it's still showing expired data structures (please refer to screenshost)

![2024-04-25 07_56_27-127 0 0 1_3278 - Browser](https://github.com/microsoft/garnet/assets/147778626/a2c5a18f-7237-4892-a369-a0f9df7c1794)
![2024-04-25 08_01_47-Memurai](https://github.com/microsoft/garnet/assets/147778626/4b0fbfba-b6bf-489b-82b5-ea21f0f777af)

**Comment by cduluCNB** [comment]
This has been resolved for strings. Thank you @TedHartMs
