### ISSUE TITLE
API Coverage - Implement SUNION

### ISSUE THREAD

**Issue by TalZaccai** [microsoft/garnet#181]
Here's your opportunity to implement a couple of RESP commands in Garnet! 

## SUNION

**Syntax:** 
`SUNION key [key ...]`

**Command description:**
Returns the members of the set resulting from the union of all the given sets.

For example:

```
key1 = {a,b,c,d}
key2 = {c}
key3 = {a,c,e}
SUNION key1 key2 key3 = {a,b,c,d,e}
```

Keys that do not exist are considered to be empty sets.

**Response:**

_Array reply:_ a list with members of the resulting set.

---

**How to approach this task:**
1. Add the new command info to the setCommandsInfoMap in the RespCommandsInfo class _(Garnet.server/Resp/RespCommandsInfo.cs)_
2. Add the new command string to the returned HashSet in the RespInfo.GetCommands method _(Garnet.server/Resp/RespInfo.cs)_
3. Add the appropriate fast parsing logic for the new command in the RespCommand.FastParseArrayCommand method (use other commands as reference) _(Garnet.server/Resp/RespCommand.cs)_
4. Implement the wrapper method to the storage layer in StorageSession _(Garnet.server/Storage/Session/ObjectStore/SetOps.cs)_
5. Define a new method in IGarnetAPI and implement it in GarnetApiObjectCommands, calling the method you have implemented in step #4 _(Garnet.server/API/IGarnetAPI.cs, Garnet.server/API/GarnetApiObjectCommands.cs)_
6. Add a new method to the RespServerSession class which will call the storage API and return the appropriate response _(Garnet.server/Resp/Objects/SetCommands.cs)_
8. Add a new method to SetObjImpl which will perform the required operation on the hash object _(Garnet.server/Objects/Set/SetObjectImpl.cs)_
9. Add a new enum value to SetOperation and add the appropriate case to the switch in SetObject.Operate, in which you will call the method defined in step #8 _(Garnet.server/Objects/Set/SetObject.cs)_
10. Add an appropriate case to the switch in TransactionManager.SetObjectKeys (Garnet.server/Transaction/TxnKeyManager.cs)
11. Add tests for the new command in the RespSetTests class _(Garnet.test/RespSetTests.cs)_

**Tip:** First add a simple test that calls the new command and use it to debug as you develop, it will make your life much easier!

If you have any questions, the Garnet team is here to help!

**Comment by argsno** [comment]
I want to give it a try

**Comment by TalZaccai** [comment]
> I want to give it a try

Go for it! LMK if you have any questions :)

**Comment by argsno** [comment]
@TalZaccai I need help with how to delete an existing key (especially if it is in the main store) when storing the value.

**Comment by roncrush** [comment]
@TalZaccai Is there going to be a separate issue for SUNIONSTORE?

**Comment by TalZaccai** [comment]
> @TalZaccai Is there going to be a separate issue for SUNIONSTORE?

Yes, I was waiting for SUNION to be merged before posting :)
