### ISSUE TITLE
Publish docker image on Docker Hub

### ISSUE THREAD

**Issue by Inv1x** [microsoft/garnet#205]
Since project becoming a better alternative to other in-memory databases, I think it would be nice to have an official image on Docker Hub

**Comment by badrishc** [comment]
Our official images are on GitHub already - see this link: 

https://microsoft.github.io/garnet/docs/welcome/releases

And this: https://github.com/microsoft/garnet/pkgs/container/garnet

Hope this helps!

**Comment by Alldrich** [comment]
But can it be hosted, under mcr.microsoft.com like [Official images for the .NET SDK](https://hub.docker.com/_/microsoft-dotnet-sdk/) so that the container can be easily found by search in Docker Hub?

**Comment by badrishc** [comment]
Possibly, it is not trivial to get images hosted there, but we will look into it. cc @darrenge
