### ISSUE TITLE
[Question] Has Any plans Publishing  official  installation on Windows or Linux?

### ISSUE THREAD

**Issue by eveloki** [microsoft/garnet#206]
Do you have any plans to release official Windows installation packages, such as MSI or EXE files, in reference to your previous maintenance work on the Redis Windows project?
Anyway，We need Linux  official installation ,Like RPM.
I am aware that Docker has become the prevalent choice, however, within numerous legacy industrial projects, there exists a preference for independent deployment of the respective services. This preference is particularly strong when it comes to the Windows platform, where these services are expected to operate autonomously. Hence, I remain hopeful that the official provider would offer a reliable installation program capable of automatically registering the service as a native Windows service.
```[tasklist]
### Tasks
```

**Comment by darrenge** [comment]
We are working through the different options on what we will release and how we release them. Unfortunately, at this time, I can't give you more detailed info other than it is being thought of and what, when and how are still TBD.

**Comment by skrlance** [comment]
I understand that it is to be decided but seems like good things always takes time! I am eagerly waiting for installable RPM files to use on my EL9 servers. Thanks! Or, at-least make .spec file available so we can compile.
