### ISSUE TITLE
Handle operations on keys of different type

### ISSUE THREAD

**Issue by vazois** [microsoft/garnet#218]
Correctly handle operations issued for keys of different type.
This issue is apparent for any pair of object commands.
Below presented an example of current behavior and expected behavior.

Current behavior

![image](https://github.com/microsoft/garnet/assets/96085550/4f0afebb-6dbc-45b9-8556-f9bb6efd04b6)

Expected behavior

![image](https://github.com/microsoft/garnet/assets/96085550/cd9bb958-c148-4426-9e77-b3abfac6114f)

**Comment by badrishc** [comment]
Rough prototype of a fix is here - https://github.com/microsoft/garnet/compare/obj-store-wrongtype?expand=1 but this needs to be refined and expanded to cover the surface.
