### ISSUE TITLE
Char that occupy multiple bytes in string as key or value would make GarnetClient.ExecuteForStringResultAsync() unable to continue execution.

### ISSUE THREAD

**Issue by luojin765** [microsoft/garnet#236]
When execute "await GarnetClient.ExecuteForStringResultAsync("123213", "值123")" using special characters (such as Chinese characters) in key or value, the method will be stucked and unable to continue execution.

I debugged the codes, and observed that, In "RespWriteUtils.cs", there is a "WriteBulkString" method.

```csharp
// RespWriteUtils.cs
/// <summary>
/// Write bulk string
/// </summary>
public static bool WriteBulkString(ReadOnlySpan<char> item, ref byte* curr, byte* end)
{
    var itemDigits = NumUtils.NumDigits(item.Length);
    int totalLen = 1 + itemDigits + 2 + item.Length + 2;
    if (totalLen > (int)(end - curr))
        return false;

    *curr++ = (byte)'$';
    NumUtils.IntToBytes(item.Length, itemDigits, ref curr);
    WriteNewline(ref curr);
    Encoding.UTF8.GetBytes(item, new Span<byte>(curr, item.Length));
    curr += item.Length;
    WriteNewline(ref curr);
    return true;
}
```

The calculation of NumDigits and the length of Span<byte> are using the length of item (ReadOnlySpan<char>) directly. However, in "GarnetClient.cs",  "Encoding.UTF8.GetByteCount()“ method was used to calculate the length of string. If the char occupies multiple bytes,  the length of ReadOnlySpan<char> will be different with the length of byte[] length. 

```csharp
// GarnetClient.cs
 async ValueTask InternalExecuteAsync(TcsWrapper tcs, Memory<byte> op, string param1 = null, string param2 = null, CancellationToken token = default)
 {     
     if (param1 != null)
     {
         int len = Encoding.UTF8.GetByteCount(param1);
         totalLen += 1 + NumUtils.NumDigits(len) + 2 + len + 2;
         // other codes .....

     }
     if (param2 != null)
     {
         int len = Encoding.UTF8.GetByteCount(param2);
         totalLen += 1 + NumUtils.NumDigits(len) + 2 + len + 2;
         // other codes .....
     }

     // ...

}

```

I tried using Encoding.UTF8.GetByteCount(item) instead of item.length when dealing with byte arrays related in the above "WriteBulkString()" medhod, then the problem could be resolved in my case.

**Comment by badrishc** [comment]
@PaulusParssinen - could this be related to your recent PR?

**Comment by PaulusParssinen** [comment]
> @PaulusParssinen - could this be related to your recent PR?

Seems like it. This was what I feared by not being explicit about the encoding in use on each `WriteBulkString` op.

You can assign this one to me. I'd propose adding seperate `WriteUtf8BulkString` overload to make it clear it doesn't rely on the assumption of input being ASCII (this overload would do correct size calc).

**Comment by PaulusParssinen** [comment]
Oh wait, I confused PR merges.. I can address this in #223 and add regression test for this.

**Comment by badrishc** [comment]
Sounds good
