### ISSUE TITLE
Timeout after particular command sequence

### ISSUE THREAD

**Issue by nightroman** [microsoft/garnet#251]
Use the below steps to reproduce the timeout (hopefully, if it is reliably reproducible).

(1) Start the default Garnet server, ideally with `--logger-level Debug`

(2) Run the below code (or use the ready attached console app project).
It works fine on the first run and we can see complete session cycles logged:

```
10::47::21 dbug: GarnetServer[0] [:3278] Accepted TCP connection from 127.0.0.1:50991
10::47::21 dbug: Session[0] [:3278] [127.0.0.1:50992] [009A2F17] Starting RespServerSession
10::47::21 dbug: Session[0] [:3278] [127.0.0.1:50991] [02B89EAA] Disposing RespServerSession
```

(3) Run the code again. In my case it always times out on the second and next runs.
Incomplete session cycles during waiting suggest that waiting happens on the server:

```
10::47::28 dbug: GarnetServer[0] [:3278] Accepted TCP connection from 127.0.0.1:50995
10::47::28 dbug: Session[0] [:3278] [127.0.0.1:50995] [02A42D56] Starting RespServerSession
```

The client code (or use the ready attached console app project):
[GarnetIssue1.zip](https://github.com/microsoft/garnet/files/14895137/GarnetIssue1.zip)

```csharp
using StackExchange.Redis;

using var redis = ConnectionMultiplexer.Connect("localhost:3278");
var db = redis.GetDatabase();

var key = "test:issue";

db.StringSet(key, "a");

db.KeyDelete(key);
db.SetAdd(key, "b");

db.KeyDelete(key);
db.ListRightPush(key, "c");
```

Environment:

- Garnet 1.0.4 (I think 1.0.3 has the same issue).
- StackExchange.Redis 2.7.33
- Windows 11

**Comment by vazois** [comment]
By default, if the --bind is not specified Garnet will use the LAN IP. You can start the server --logger-level=Trace and see the view the server IP address as in the below example. I think that is the issue which results in SERedis not connecting.

![image](https://github.com/microsoft/garnet/assets/96085550/64e6c2d5-69f7-4132-b40a-75d5787c3245)

**Comment by nightroman** [comment]
I am not sure about the answer (was it an advice?). Is this the configuration issue? What should I specify as --bind?

> I think that is the issue which results in SERedis not connecting.

I am not sure what this means, too. SERedis is connecting and works as such. Here are some tests, all pass with "default Garnet"
https://github.com/nightroman/FarNet.Redis/tree/main/tests

But the particular sequence of "simple" commands (provided) causes timeouts.

**Comment by vazois** [comment]
It's alright I think there was a confusion with the IP you provided and was not able to repro your issue.
The issue was that DEL had bug and was not working properly. Created a PR to fix this issue https://github.com/microsoft/garnet/pull/284. 
Run your example and it seems to work fine.

**Comment by nightroman** [comment]
@vazois Thank you, I cannot reproduce this issue with the latest. Closing and looking forward to Microsoft.Garnet 1.0.6 at NuGet
