### ISSUE TITLE
Secret comparisons should be constant time

### ISSUE THREAD

**Issue by SteveSyfuhs** [microsoft/garnet#256]
Any time a symmetric secret whether cleartext, hashed, or encrypted, is compared to another value it needs to use a constant time comparison function. If this isn't done, the secret material is leaked whenever a negative comparison occurs.

```csharp
var a = "foo";
var b = "bar";
var c = "foobar";

a == a // foo == foo 3/3
a == b // foo == bar 0/3
a == c // foo == foobar 3/6
```

First comparison leaks nothing. Second comparison tells us it's three characters. Third tells us it's at least three characters and the first three are "foo".

**Comment by badrishc** [comment]
Good find, thanks!
