### ISSUE TITLE
Passwords are hashed using SHA256

### ISSUE THREAD

**Issue by SteveSyfuhs** [microsoft/garnet#258]
Is this a function of the Redis protocol or is this an internal implementation detail?

https://github.com/microsoft/garnet/blob/5675a98d752950df8dc33894bd45358fa9adf049/libs/server/ACL/ACLPassword.cs#L35-L39

If this is an implementation detail then this needs to be converted into something more time consuming using a KDF plus salt.

**Comment by eveloki** [comment]
Redis internally stores passwords hashed with SHA256.

https://redis.io/docs/management/security/acl/

**Comment by lmaas** [comment]
We chose to use plain SHA-256 hashes to ensure compatibility with Redis’s ACL rules. However, we are actively exploring improvements, such as introducing an optional syntax for salted hashes and potentially transitioning to a more compute-intensive KDF. While addressing this isn’t our top priority at the moment, we are aware of this issue and will address it in the future.

**Comment by SteveSyfuhs** [comment]
Makes sense. I also see you're adding in AAD support as well, which is probably the better long-term approach anyway. If and when you get to improving the hashing feel free to reach out to me internally (stsyfuhs@ms) if you're inclined. My team owns Windows auth so we have an abundance of lessons learned around protocol auth.
