### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by careless6666** [microsoft/garnet#260]
Unfortunately, I didn’t see any documentation on how to monitor server health and solve troubleshooting problems, such as memcached
Do you have plans to add this?
<img width="1724" alt="Screenshot 2024-04-08 at 10 58 34 AM" src="https://github.com/microsoft/garnet/assets/8223175/3a5fa95a-887d-4121-b77b-8f404ebe565e">

**Comment by vazois** [comment]
You can use RedisInsight for visualization. In addition, you can have access to server metrics by setting up you instances using --metrics-sampling-freq and --latency-monitor flags (https://microsoft.github.io/garnet/docs/getting-started/configuration).
You can access those metrics using INFO command (i.e. INFO stats) or LATENCY HISTOGRAM.

**Comment by careless6666** [comment]
Great, thanks!
