### ISSUE TITLE
SETNX is not implemented

### ISSUE THREAD

**Issue by yeurch** [microsoft/garnet#270]
The [API Compatibility](https://microsoft.github.io/garnet/docs/commands/api-compatibility#string) document suggests that `SETNX` (set a string value when it does not already exist) is implemented in Garnet, but this does not seem to be the case.

Using `redis-cli` to connect to Garnet:

```
$ ./redis-cli -p 3278
127.0.0.1:3278> setnx key1 val1
(error) ERR unknown command
```

The problem can also be illustrated by the following C# snippet using `StackExchange.Redis`:

```csharp
using StackExchange.Redis;

ConnectionMultiplexer redis = ConnectionMultiplexer.Connect("localhost:3278");
IDatabase db = redis.GetDatabase();

// Use SETNX to set a key if it does not exist
db.StringSet("my_key", "value1", null, When.NotExists);
db.StringSet("my_key", "This value should never be seen", null, When.NotExists);

var result = db.StringGet("my_key");
Console.WriteLine(result);
```

**Actual Result**

This code throws a `RedisServerException` at runtime with the message "ERR unknown command", but it works correctly when ran against actual Redis server.

**Expected Result**

The code should run without error, and the final value of the string key "my_key" is "value1" and is printed to the console.

**Comment by TalZaccai** [comment]
Hi @yeurch! Thanks for bringing that to our attention. That's a mistake in the API Compatibility page, I'll have it updated.

In any case, SETNX is now considered deprecated by Redis (https://redis.io/docs/latest/commands/setnx/), and can be replaced with running SET with the NX argument, do I don't believe we'll be implementing that one, unless there's a specific need.

If you're using SERedis, you can run `(string)db.Execute($"SET", key, value, "NX"` instead

**Comment by yeurch** [comment]
Thanks for digging into this @TalZaccai.  I hadn't realized that the command was deprecated, sorry.  I guess this could be a philosophical debate ... does Garnet intend to be fully compatible with Redis?  If so, I'd argue these _should_ be implemented, otherwise it's not 100% compatible.  But they've been marked as deprecated for so long by Redis that I guess it's a tough call.

Another interesting point is that `StackExchange.Redis`, which you mention in your very first bullet point in the README, appears to use `SETNX key val` rather than `SET key val NX`.  If this client is widely in use, then I think it could cause issues for many users.  `db.SetString()` seems to be the "normal" way to do sets from SERedis, and having to switch to the lower level `db.Execute("SET", ...)` could cause confusion.

**Comment by badrishc** [comment]
@marcgravell - do you know under what condition `db.StringSet("my_key", "value1", null, When.NotExists)` in SE.Redis would use the deprecated `SETNX` versus what Garnet supports, `SET .. NX`?

**Comment by mgravell** [comment]
Looks like it universally prefers SETNX - at least when dealing with Redis,
this gives wider coverage without needing a server version check

(
https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/RedisDatabase.cs#L4443
)

**Comment by mgravell** [comment]
For context: we frequently run into problems when defaulting to newer
commands, because generally servers support the older commands even when
they have been superceded, but many servers do not yet support the newer
commands; this could be because the server simply doesn't support it, or
could be because the instance hasn't been updated in forever, and it isn't
worth the outage. My recommendation: Garnet should support both :)
Likewise: HMSET even though HSET now allows the same functionality

**Comment by badrishc** [comment]
This makes sense, thanks!

**Comment by yeurch** [comment]
If the intent (as recommended by @mgravell) is to support both `set ... nx` and `setnx ...`, should this have been closed?
