### ISSUE TITLE
API Coverage - Implement LMPOP

### ISSUE THREAD

**Issue by TalZaccai** [microsoft/garnet#273]
Here's your opportunity to implement a RESP command in Garnet! 

## LMPOP

**Syntax:** 
`LMPOP numkeys key [key ...] <LEFT | RIGHT> [COUNT count]`

**Command description:**

Pops one or more elements from the first non-empty list key from the list of provided key names.

Elements are popped from either the left or right of the first non-empty list based on the passed argument. The number of returned elements is limited to the lower between the non-empty list's length, and the count argument (which defaults to 1).

**Response:**

One of the following:

* _Nil reply:_ if no element could be popped.
* _Array reply:_ a two-element array with the first element being the name of the key from which elements were popped and the second element being an array of elements.

---

**How to approach this task:**
1. Add the new command info to the listCommandsInfoMap in the RespCommandsInfo class _(Garnet.server/Resp/RespCommandsInfo.cs)_
2. Add the new command string to the returned HashSet in the RespInfo.GetCommands method _(Garnet.server/Resp/RespInfo.cs)_
3. Add the appropriate fast parsing logic for the new command in the RespCommand.FastParseArrayCommand method (use other commands as reference) _(Garnet.server/Resp/RespCommand.cs)_
4. Implement the wrapper method to the storage layer in StorageSession _(Garnet.server/Storage/Session/ObjectStore/ListOps.cs)_
5. Define a new method in IGarnetAPI or IGarnetReadAPI and implement it in GarnetApiObjectCommands, calling the method you have implemented in step #4 _(Garnet.server/API/IGarnetAPI.cs, Garnet.server/API/GarnetApiObjectCommands.cs)_
6. Add a new method to the RespServerSession class which will call the storage API and return the appropriate response _(Garnet.server/Resp/Objects/ListCommands.cs)_
8. Add a new method to ListObjImpl which will perform the required operation on the list object _(Garnet.server/Objects/List/ListObjectImpl.cs)_
9. Add a new enum value to ListOperation and add the appropriate case to the switch in ListObject.Operate, in which you will call the method defined in step #8 _(Garnet.server/Objects/List/ListObject.cs)_
10. Add an appropriate case to the switch in TransactionManager.ListObjectKeys (Garnet.server/Transaction/TxnKeyManager.cs)
11. Add tests for the new command in the RespListTests class _(Garnet.test/RespListTests.cs)_

**Tip:** First add a simple test that calls the new command and use it to debug as you develop, it will make your life much easier!

If you have any questions, the Garnet team is here to help!

**Comment by Zombach** [comment]
I'm interested in taking a stab at this!

**Comment by TalZaccai** [comment]
> @TalZaccai I'm interested in taking a stab at this!

Go for it! LMK if you have any questions!

**Comment by TalZaccai** [comment]
@Zombach any progress here? :)

**Comment by Zombach** [comment]
> @Zombach any progress here? :)
Hi I've been busy with this [Add Garnet in Aspire](https://github.com/dotnet/aspire/pull/3839)

I'll get it done this weekend. 
I'll post on Monday what came of it.
Или не получилось.

**Comment by Zombach** [comment]
Unfortunately, I don't have time for this task. Hope someone else implements this.

**Comment by funcmike** [comment]
@TalZaccai  I can do this. I'll write in a few days how I'm doing.

**Comment by funcmike** [comment]
@TalZaccai Ok so basic support is working. Can you please review my code?
I also have questions about:

>7.  Add a new method to ListObjImpl which will perform the required operation on the list object (Garnet.server/Objects/List/ListObjectImpl.cs)
>8. Add a new enum value to ListOperation and add the appropriate case to the switch in ListObject.Operate, in which you will call the method defined in step #8 (Garnet.server/Objects/List/ListObject.cs)
>9. Add an appropriate case to the switch in TransactionManager.ListObjectKeys (Garnet.server/Transaction/TxnKeyManager.cs)

LMPOP is a operation on many lists when it's just on one list it's the same as LPOP/RPOP (which are more straightforward imho).
For now I skipped it because I don't get it what's the point of implementing it in these files - maybe I'm miss understand something?

**Comment by TalZaccai** [comment]
> @TalZaccai Ok so basic support is working. Can you please review my code? I also have questions about:
> 
> > 7. Add a new method to ListObjImpl which will perform the required operation on the list object (Garnet.server/Objects/List/ListObjectImpl.cs)
> > 8. Add a new enum value to ListOperation and add the appropriate case to the switch in ListObject.Operate, in which you will call the method defined in step #8 (Garnet.server/Objects/List/ListObject.cs)
> > 9. Add an appropriate case to the switch in TransactionManager.ListObjectKeys (Garnet.server/Transaction/TxnKeyManager.cs)
> 
> LMPOP is a operation on many lists when it's just on one list it's the same as LPOP/RPOP (which are more straightforward imho). For now I skipped it because I don't get it what's the point of implementing it in these files - maybe I'm miss understand something?

@funcmike You are correct, those are only relevant for single-key operations (my apologies, I copy & pasted this explanation from a former task)
