### ISSUE TITLE
[BUG]: INCR DECR operation zero - "ERR value is not an integer or out of range."

### ISSUE THREAD

**Issue by catchv** [microsoft/garnet#290]
### Describe the bug

If a number is set to 0 using INCR or DECR, the INCR and DECR operations can no longer be used.

### Steps to reproduce the bug

* case 1
127.0.0.1:6379> INCR key100
(integer) 1
127.0.0.1:6379> INCR key100
(integer) 2
127.0.0.1:6379> DECR key100
(integer) 1
127.0.0.1:6379> DECR key100
(integer) 0
127.0.0.1:6379> DECR key100
(error) ERR value is not an integer or out of range.
127.0.0.1:6379> INCR key100
(error) ERR value is not an integer or out of range.
127.0.0.1:6379> 

* case 2
127.0.0.1:6379> SET key101 0
OK
127.0.0.1:6379> INCR key101
(error) ERR value is not an integer or out of range.

### Release version

127.0.0.1:6379> INFO SERVER
# Server
garnet_version:1.0.5
garnet_mode:standalone
os:Unix 6.6.16.0
processor_count:8
arch_bits:64
uptime_in_seconds:45
uptime_in_days:0
monitor_task:disabled
monitor_freq:0
latency_monitor:disabled
run_id:2004b00cc75ed9f0b0b6496173deb77ceb17d657
redis_version:6.2.11

### IDE

redis-cli

### OS version

MAC M1 - docker - ghcr.io/microsoft/garnet:latest

**Comment by tisilent** [comment]
```
> 127.0.0.1@3278 connected!
> set key1 0
OK
> decrby key1 50
ERR value is not an integer or out of range.
```
