### ISSUE TITLE
Expand storage device from azure to other clouds, such as AWS, google cloud, Ali Cloud, Huawei Cloud, etc .

### ISSUE THREAD

**Issue by springmin** [microsoft/garnet#299]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

only is expend the storage device. 

### Describe the solution you'd like

1、Tsavorite.devices.AzureStorageDevice project split into two projects: ①public interface and common implementation, ② Azure Specific implementation;
2、any cloud can create a specific project to implement the device  based on its OBS SDK.

**Comment by badrishc** [comment]
As Paulus mentions, this is already the case. With the `IDevice` abstraction, any cloud can implement their specific device for their cloud.
