### ISSUE TITLE
Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by chunhuijiang** [microsoft/garnet#310]
### Describe the bug

In the TsavoriteBase file，
method：internal void Initialize(int version, long size, int sector_size)，
and the code-->state[version].tableRaw = GC.AllocateArray<HashBucket>((int)(aligned_size_bytes / Constants.kCacheLineBytes), true);
When the computer's used memory is greater than 85% or 90%, <Exception of type 'System.OutOfMemoryException' was thrown. > error will be reported

### Steps to reproduce the bug

1. Run more apps
2. When the computer's used memory is greater than 85% or 90%
3. Run the GarnetServer.exe  or Start debugging the GarnetServer project

### Expected behavior

Exception of type 'System.OutOfMemoryException' was thrown.

### Release version

v1.0.5

### IDE

Visual Studio 2022

### OS version

Window 11

### Additional context

Exception of type 'System.OutOfMemoryException' was thrown.

**Comment by badrishc** [comment]
You can configure the index (-i) and memory (-m) size when starting the server. The defaults will need to be adjusted when you have limited memory.
