### ISSUE TITLE
SCAN command returns keys of expired data structures

### ISSUE THREAD

**Issue by cduluCNB** [microsoft/garnet#326]
### Describe the bug

Thank you @TedHartMs for fixing #151 for strings, now I'm seeing the same behavior for data structures where expired keys are showing in a SCAN. Apologies that I should have tried testing the data structures in addition to strings.

![2024-04-25 07_56_27-127 0 0 1_3278 - Browser](https://github.com/microsoft/garnet/assets/147778626/39839032-d886-408e-8f6d-9cd6ee58286a)
![2024-04-25 08_01_47-Memurai](https://github.com/microsoft/garnet/assets/147778626/9daf7785-e380-4244-992b-8f36a1fac496)

### Steps to reproduce the bug

Add any data structure type with an expiry (Hash, List, Set, Sorted Set) and wait until it expires.

Run the SCAN command (i.e. SCAN *)

### Expected behavior

The expired data structures should not appear in the list when SCAN is run.

### Release version

v1.0.6

### OS version

Windows 11

**Comment by TedHartMS** [comment]
> I should have tried testing the data structures in addition to strings.

That makes two of us :) Thanks for the catch!

**Comment by cduluCNB** [comment]
Thank you @TedHartMS! Verified working with the latest version of main. I can finally use RedisInsight properly now!
