### ISSUE TITLE
Precompiled binaries

### ISSUE THREAD

**Issue by dceravigupta** [microsoft/garnet#34]
Are there any plans to release precompiled and signed binaries to simplify the process of hosting a standalone Garnet based cache?

**Comment by talw-nym** [comment]
I'll add that I can't find any official docker files for use on docker hub ☹

**Comment by badrishc** [comment]
The Dockerfile variants are in the root folder of the repo here: https://github.com/microsoft/garnet. We are not yet hosting containers ourselves, but for now anyone in the community can host it. More details: https://microsoft.github.io/garnet/docs/welcome/releases#docker

**Comment by pl4nty** [comment]
@talw-nym I've built and tested a signed Linux amd/arm image here: `ghcr.io/pl4nty/garnet@sha256:07247278d5bd716063687feaf340f5271dbc41875835dc53fb552031311944b9`

I'll work on Windows tonight, since WCOW BuildKit support recently released

**Comment by badrishc** [comment]
Wonderful, thanks!

**Comment by yzy613** [comment]
I built an image and pushed it to docker hub, which can be used directly. :v:
> https://hub.docker.com/r/yzy613/garnet

**Comment by lc6464** [comment]
Here is a docker-free console application: [GarnetServer](https://github.com/lc6464/GarnetServer) 😊

**Comment by pl4nty** [comment]
@badrishc I hit a known issue with nested folders so couldn't compile natively on Windows, but I was able to cross-compile with some refactoring. It can be much faster in some build topologies like local builds, and allows exotic architectures like s390x (IBM z). This image has Linux amd/arm and Windows Nano Server: `ghcr.io/pl4nty/garnet@sha256:3f48d012023ca4eb28f5cd14867d747e49f4e9037e279de696726c7cc133b3eb`

I'm happy to send a PR, but I used prerelease Dockerfile syntax so it might not be ready to merge yet.

**Comment by badrishc** [comment]
> Here is a docker-free console application: [lc6464/GarnetServer](https://github.com/lc6464/GarnetServer) 😊 I compiled binaries for `win-x64` `win-arm64` `linux-x64` `linux-arm64` `osx-arm64` and `osx-x64` ❤️

Just a question - how does your wrapper differ from the console application we have here: https://github.com/microsoft/garnet/tree/main/main/GarnetServer

**Comment by lc6464** [comment]
> > Here is a docker-free console application: [lc6464/GarnetServer](https://github.com/lc6464/GarnetServer) 😊 I compiled binaries for `win-x64` `win-arm64` `linux-x64` `linux-arm64` `osx-arm64` and `osx-x64` ❤️
> 
> Just a question - how does your wrapper differ from the console application we have here: https://github.com/microsoft/garnet/tree/main/main/GarnetServer

Obviously, no difference. I only published some binaries. 🥰

**Comment by douglasg14b** [comment]
An official dockerhub image would be very desirable for this. Almost every place where I can think of using this would require deployment via docker.

**Comment by pomazanbohdan** [comment]
https://github.com/pomazanbohdan/garnet-docker-compose

**Comment by skrlance** [comment]
Hi, I want to try out the Garnet but I am stuck by not getting precompiled RPM file for Enterprise Linux 9? Please make them available soon!

**Comment by Niek** [comment]
Added a PR to add official multi-arch docker images: https://github.com/microsoft/garnet/pull/107

**Comment by skrlance** [comment]
I don't use docker, I just need direct installation rpm file

**Comment by lc6464** [comment]
> I don't use docker, I just need direct installation rpm file

You can use latest release of my repo
https://github.com/lc6464/GarnetServer

**Comment by skrlance** [comment]
> > I don't use docker, I just need direct installation rpm file
> 
> You can use latest release of my repo https://github.com/lc6464/GarnetServer

There is no "rpm" file to install in your repo? I am not a programmer to compile or build! Kindly

**Comment by lc6464** [comment]
> There is no "rpm" file to install in your repo? I am not a programmer to compile or build! Kindly

No, you can use `wget` to download [linux-x64-based.tar.xz](https://github.com/lc6464/GarnetServer/releases/download/v1.0.0/linux-x64-based.tar.xz) .

**Comment by skrlance** [comment]
Download and where to put these three files to run Garner Server?
1. libnative_device.so
2. GarnetServer.pdb
3. GarnetServer

**Comment by lc6464** [comment]
> Download and where to put these three files to run Garner Server?
> 
> 1. libnative_device.so
> 2. GarnetServer.pdb
> 3. GarnetServer

You can put anywhere you want, and execute `./GarnetServer` in that directory.
But you should ensure dotnet has been installed.

**Comment by darrenge** [comment]
We now have container packages here: https://github.com/microsoft/garnet/pkgs/container/garnet   Any future containers will be put in this place too but what we put here is TBD. As for putting out containers in Docker Hub or Microsoft Artifact Registry is also TBD.
