### ISSUE TITLE
No data on restart despite persistence enabled

### ISSUE THREAD

**Issue by ThomasWeiss** [microsoft/garnet#360]
### Describe the bug

I was trying to test Garnet's persistence support but was unable to retrieve my data after a restart.

### Steps to reproduce the bug

1. Start GarnetServer with `--storage-tier true`
2. Ingest a bunch of keys
3. Issue a `SAVE` command (`SAVE` returns `OK`)
4. Confirm that files have been created on disk
5. Close, then restart GarnetServer with `--storage-tier true`
6. Issue a `DBSIZE` command, returns `0`

### Expected behavior

Data initially ingested is expected to be found after restart.

### Release version

v1.0.7

### OS version

Windows 11

**Comment by badrishc** [comment]
You need to restart withb the `--recover` flag.

**Comment by ThomasWeiss** [comment]
Missed this option from the docs, that worked thanks!
