### ISSUE TITLE
API Coverage - Lua scripting or workaround

### ISSUE THREAD

**Issue by KeithHenry** [microsoft/garnet#366]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

Garnet does not support Lua, which prevents it from being able to replace Redis.

However, we mainly use Lua to workaround issues in Redis, most significantly that `MSET` does not support expiry.

We had issues in production due to queued up `SETEX` when batch storing. Our workaround looks like this:

```c#
namespace ...
using StackExchange.Redis;

public static class RedisDatabaseExtension {

    /// <summary>Set a batch of keys to the string values with the given expiry.
    /// <para>MSET does not support setting expiry, but is better if values don't expire.</para>
    /// <para>EVAL a Lua script to call SETEX for every record in the batch.</para>
    /// <para>In any batches fail this will return false, and not execute further batches.</para>
    /// <seealso cref="https://redis.io/commands/eval/"/></summary>
    /// <param name="db">Redis DB to extend.</param>
    /// <param name="batchSize">Number of records in each batch.</param>
    /// <param name="expiresSeconds">Number of seconds to set as the expiry.</param>
    /// <param name="items">Collection of key-value pairs to set.</param>
    /// <returns>True if all scripts evaluated successfully, false if any failed to match the number of records input in a batch.</returns>
    public static async Task<bool> StringSetLuaBatch(
        this IDatabase db, 
        int batchSize, 
        int expiresSeconds,
        params (RedisKey key, RedisValue value)[] items) {

        // ARGV[1] is the expiry, so all the values are off-by-one compared to their keys
        const string lua = """
            local expiry = tonumber(ARGV[1])
            local count = 0
            for i, key in ipairs(KEYS) do
                redis.call('SETEX', key, expiry, ARGV[i+1])
                count = count + 1
            end
            return count
            """;

        List<RedisKey> keys = new(batchSize);
        List<RedisValue> values = new(batchSize + 1) { expiresSeconds };

        foreach(var (key, value) in items)
        {
            keys.Add(key);
            values.Add(value);

            if(keys.Count == batchSize)
            {
                if(keys.Count != (int) await db.ScriptEvaluateAsync(lua, [.. keys], [.. values]))
                    return false; // Count doesn't match, exit early with failure

                // Reset for next batch
                keys.Clear();
                values.Clear();
                values.Add(expiresSeconds);
            }
        }

        if (keys.Count != 0) // If any left over execute final batch
            if(keys.Count != (int) await db.ScriptEvaluateAsync(lua, [.. keys], [.. values]))
                return false; // Count doesn't match, exit early with failure

        return true;
    }
}
```

Lua lets us send one batch to Redis, and then Lua handles the `SETEX` loop.

### Describe the solution you'd like

Lua scripting to work, so Garnet can be a drop-in replacement.

### Describe alternatives you've considered

Everything else is nastier to support - diverge from RESP so `MSET` can expire? Alternate to Lua scripts (C# scripts?) Some batching/networking cleverness so the queue of `SETEX` doesn't block it up?

**Comment by badrishc** [comment]
> We had issues in production due to queued up SETEX when batch storing.

This is probably a Redis-specific issue. Garnet should do fine with `SETEX` sent by `StackEchange.Redis` which internally does adaptive batching. Perhaps try this out.

**Comment by badrishc** [comment]
The linked PR https://github.com/microsoft/garnet/pull/369 augments custom stored procedures to support a variable number of parameters (similar to `MSET`) and further uses this to implement `MSETPX` as a custom transaction.

**Comment by KeithHenry** [comment]
> This is probably a Redis-specific issue. Garnet should do fine with `SETEX` sent by `StackEchange.Redis` which internally does adaptive batching. Perhaps try this out.

@badrishc possibly, it was a time consuming issue to reproduce and the result was an outage at a busy time so it would need testing. We're using `StackEchange.Redis` and Redis should have done fine with the long queue of `SETEX` too - I don't know whether the issue was with `StackEchange.Redis` or Redis itself, the symptom was that the queue of `SETEX` blocked any requests to Redis.

> The linked PR #369 augments custom stored procedures to support a variable number of parameters (similar to `MSET`) and further uses this to implement `MSETPX` as a custom proc.

Interesting - so like a CLR function in SQL Server you can have custom .NET sprocs? I didn't realise Garnet could do that. I'll definitely check it out.

The main issue (with both suggestions) is that this would need a different build - we'd have a Garnet compatible version and a Redis compatible version and despite Redis's recent close-sourcing we have a _lot_ of existing Redis. At best we have additional config settings and different code paths for different providers - that's real cost, especially as we're going to have production Redis around for a while to come even if we started migrating to Garnet tomorrow.

**Comment by badrishc** [comment]
> Redis should have done fine with the long queue of SETEX too

Redis being single threaded processing on the server side, would have choked on this scenario, even if the StackExchange client did the right thing, unfortunately.

> The main issue (with both suggestions) is that this would need a different build

The way you would use `StackExchange.Redis` for this would be something like:

https://github.com/microsoft/garnet/blob/844fedd1340230fdb2173cb61dc404eb3a96f52e/test/Garnet.test/RespTransactionProcTests.cs#L388-L389

**Comment by badrishc** [comment]
Closing as per provided workarounds, thanks!
