### ISSUE TITLE
GarnetClient Extensions

### ISSUE THREAD

**Issue by hishamco** [microsoft/garnet#375]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

While there are few implemented commands for `GarnetClient` are you open to accepting PRs for implementing other commands on top of `ExecuteForStringResultAsync()` or `ExecuteForStringArrayResultAsync()`

I find myself writing some here https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/blob/main/src/OrchardCoreContrib.Garnet/Extensions/GarnetClientExtensions.cs

Also there are two in this PR https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/pull/127/files

### Describe the solution you'd like

Add extension methods to `GarnetClient`

**Comment by badrishc** [comment]
Yes, we are definitely open to accepting pull requests in this space. Thanks, and look forward to it!

**Comment by hishamco** [comment]
Believe it or not yesterday I planned to start my library but I thought it be better to file an issue than hear the response, @badrishc could you please look for one of the extensions that I created if it's fine I can start push a PR

BTW shall we add it as extension methods or where should I add them, coz it's the first time to contribute here

**Comment by badrishc** [comment]
These can be added at https://github.com/microsoft/garnet/tree/main/libs/client/GarnetClientAPI - you will see there are already files for different API categories, such as Sorted Set. You would add the new ones similarly.

**Comment by hishamco** [comment]
Got it, I will start my PRs :)

One more thing but it might be breaking change why you are using `Garnet.client` namespace instead of `Garnet.Client` it against the namespace rules

**Comment by badrishc** [comment]
It was just a stylistic choice. We can leave it as `Garnet.client` - it is fine as long as our format style does not complain.

**Comment by PaulusParssinen** [comment]
+1 for following the standard practice of PascalCasing the namespaces.
