### ISSUE TITLE
LightClientRequest very bad coding habit

### ISSUE THREAD

**Issue by ShaolanTech** [microsoft/garnet#376]
### Describe the bug

LightClientRequest is simple, but very import,  and many code will be depend on it in the future. Your team should consider recoding this class by some experienced engineers, but not a student or a junior programmer.
by simple reviewing the code, i found lots bad coding habits, for example: arbitrarily allocate array with "new", and concate string with "+".

### Steps to reproduce the bug

1.just open LightClientRequest.cs

### Expected behavior

consider to use ArrayPool and ReadOnlySpan

### Screenshots

![图片](https://github.com/microsoft/garnet/assets/25076349/8a9177ac-d97d-41f7-be36-b7cf3c22daaa)
![图片](https://github.com/microsoft/garnet/assets/25076349/41ff16c0-d050-4442-9f32-b912336908dc)

### Release version

v1.08

**Comment by PaulusParssinen** [comment]
Be the change you want see in the world and submit a PR 😉

**Comment by badrishc** [comment]
Not every code fragment you see in a repo is part of what goes into production. There are usually prototypes, test code, code for benchmarking, etc. that are there to achieve narrow purposes. LightClient in particular is only used in this way. As Paulus mentions, happy to receive pull requests.
