### ISSUE TITLE
100% mem and disk usage, when use "save" cmd

### ISSUE THREAD

**Issue by sun51586** [microsoft/garnet#380]
### Describe the bug

when use "save" cmd in Another Redis Desktop Manager, 100% mem(from 6.1G up to 15.1G) and 100% disk usage(write c:\windows\system32\store\checkpointxxx,c:\windows\system32\objectstore\xxx).
my config：
{
	"Port" : 6379,
	"MemorySize" : "1g",
	"LogDir": "c:\\temp\\_garnet\\",
	"EnableStorageTier": true,
	/*"EnableAOF": true*/
}
use nuget v1.0.8 ,in .net 8 woker service project, host in windows service.
Is that my config error or bug?

### Steps to reproduce the bug

1,start garnet service.the cache is empty.
2,open Another Redis Desktop Manager V1.5.2.
3,input cmd "set ka aaa" enter,"set kb bbb" enter,then input “save" enter。
4,garnet process write c:\windows\system32\stroe\checkpoint** crazy ,and memory up to the max.

### Release version

V1.0.8

### OS version

windows 10 pro 22h2

**Comment by badrishc** [comment]
1. The default hash table size is unfortunately set to very high (`8g`) so this is an expensive flush operation. Please use `--index` to reduce the hash table size to a reasonable size such as `1m`. See [this link](https://microsoft.github.io/garnet/docs/getting-started/memory#index-size) for how to configure hash size for your workload. We will update Garnet to use a better default.
2. You have not specified checkpointdir so the checkpoint will get written in the default location. Suggest you use `--checkpointdir` to specify the checkpoint folder.

**Comment by sun51586** [comment]
Very Thanks..I try it.

It would be even better to give a default configuration file for diffrent usage scenarios。
