### ISSUE TITLE
It is not possible to use client tools such as datagrip or redis insight

### ISSUE THREAD

**Issue by kyuminMoon** [microsoft/garnet#383]
### Feature request type

sample request

### Is your feature request related to a problem? Please describe

I always thought this part was inconvenient while using it. Do you have any plans to create a dedicated GUI client tool or make the driver supported?

### Describe the solution you'd like

Do you have any plans to create a dedicated GUI client tool or make the driver supported?
For reference, I am using garnet cluster mode.

**Comment by badrishc** [comment]
We have made sure in the past that RedisInsight works with Garnet. Let us know if you run into any issues.

**Comment by kyuminMoon** [comment]
Currently, garnet is operated in cluster mode and is being used as a master slave structure.
When establishing a connection using intellij's Database function, the connection is established normally, but the schema is not viewed.

The versions used are as follows:
IntelliJ IDEA 2023.2.5 
garnet : 1.0.8

The script used is as follows.
```
./GarnetServer --cluster --checkpointdir='/data/' --aof

redis-cli -h garnet-m -p 6379 cluster addslots $(seq 0 16383);
redis-cli -h garnet-m -p 6379 cluster set-config-epoch 1;
redis-cli -h garnet-s1 -p 6379 cluster set-config-epoch 2;
redis-cli -h garnet-s2 -p 6379 cluster set-config-epoch 3;
redis-cli -h garnet-m -p 6379 cluster meet garnet-s1 6379;
redis-cli -h garnet-m -p 6379 cluster meet garnet-s2 6379;
redis-cli -h garnet-s1 -p 6379 cluster replicate $(redis-cli -h garnet-m -p 6379 cluster myid);
redis-cli -h garnet-s2 -p 6379 cluster replicate $(redis-cli -h garnet-m -p 6379 cluster myid);
```

We confirmed that when applying the settings, data replication proceeds without problem.
However, the schema is not being searched.
![image](https://github.com/microsoft/garnet/assets/70198505/9ea3a11e-d590-479f-84a7-7800f79c1acb)

```
DBMS: Redis (ver. 6.2.11)
Case sensitivity: plain=mixed, delimited=mixed
Driver: Redis JDBC Driver (ver. 1.5, JDBC4.2)

Ping: 17 ms

Unable to get the server mode using the "INFO server" command to check if the connection mode matches the server mode.
You can disable the connection mode verification. With the verification disabled, you need to ensure on your own that the prefix in your URL is correct (jdbc:redis:// or jdbc:redis:cluster://).
```

Is there a problem with the method I used?

**Comment by badrishc** [comment]
we have not tried with cluster, if you can debug and let us know which command is missing, we might be able to add it. cc @vazois

**Comment by kyuminMoon** [comment]
Sorry for the late reply.
When executing the CONFIG GET databases command, I confirmed that an error occurred because the result type was different.
The log is as follows.

```
CONFIG GET databases
-- ] --------------------------------------------------
-- 2024-05-16 12:09:22 [garnet] [0@10.100.100.151 [2]] [introspection] [session id: 1757844920] [statement id: 264536377] error - class [B cannot be cast to class java.util.List ([B and java.util.List are in module java.base of loader 'bootstrap')
-- 2024-05-16 12:09:22 [garnet] [0@10.100.100.151 [2]] [introspection] [session id: 1757844920] [statement id: 264536377] finished - execution time: 11 ms
-- [ --------------------------------------------------
```

Based on redis 7.2.3 version, the result is output as follows.
```
1) "databases"
2) "1"
```

However, garnet is output as follows:
```
"16"
```

**Comment by badrishc** [comment]
Good work narrowing it down, this should not be hard to fix. Thanks.

**Comment by badrishc** [comment]
@kyuminMoon - can you see if this makes your tool work or does it hit some other issue after this fix?

**Comment by kyuminMoon** [comment]
@badrishc Thank you for the quick response
After testing with intellij and datagrip, it was confirmed that it was working properly!
