### ISSUE TITLE
ltrim Command Behavior is Inconsistent with Redis

### ISSUE THREAD

**Issue by mdjs147** [microsoft/garnet#400]
### Describe the bug

> LPUSH abc  a0 a1 a2 a3 a4 a5
6
> llen abc
6
> lrange abc 0 5
a5
a4
a3
a2
a1
a0
> ltrim abc 6 -1
OK
> llen abc
1
> lrange abc 0 1
a0

### Steps to reproduce the bug

garnet 

> LPUSH abc  a0 a1 a2 a3 a4 a5
6
> llen abc
6
> lrange abc 0 5
a5
a4
a3
a2
a1
a0
> ltrim abc 6 -1
OK
> llen abc
1
> lrange abc 0 1
a0

redis 
> LPUSH abc  a0 a1 a2 a3 a4 a5
6
> llen abc
6
> lrange abc 0 5
a5
a4
a3
a2
a1
a0
> ltrim abc 6 -1
OK
> llen abc
0

### Release version

1.0.10

**Comment by TalZaccai** [comment]
Thank you for reporting this bug! Posting a fix shortly :)
