### ISSUE TITLE
bgsave Execute command memory inflation

### ISSUE THREAD

**Issue by chunjieyaya** [microsoft/garnet#401]
### Describe the bug

After executing the bgsave command in the test environment, the memory of windows is instantaneously guaranteed to 98%

### Steps to reproduce the bug

-> redis-cli -p 3278
->bgsave

### Screenshots

![1716251775800](https://github.com/microsoft/garnet/assets/43339684/2b978352-c195-4356-8727-956bda27c7fe)

### Release version

1.0.8

### OS version

windows 10

**Comment by badrishc** [comment]
* Provide server command line and sequence of client calls
* Run with `--logger-level Trace` and paste the configuration messages you see

**Comment by chunjieyaya** [comment]
Upgrade to the latest version resolved
