### ISSUE TITLE
Namespace to isolate the data between users

### ISSUE THREAD

**Issue by rnz** [microsoft/garnet#415]
### Feature request type

sample request

### Is your feature request related to a problem? Please describe

In cluster mode need separate the data between users.

### Describe the solution you'd like

```
# Auth with the requirepass
redis-cli -p 3278 -a ${REQUIREPASS}

# Add a new namespace with the token, the namespace name must be unique.
> namespace add ${NEW NAMESPACE} ${NEW TOKEN}

# Update the namespace's token
> namespace set ${NAMESPACE} ${NEW TOKEN}

# Delete the namespace
> namespace del ${NAMESPACE}

# Get the namespace's token
> namespace get ${NAMESPACE}

# List namespaces
> namespace get *

#Switch namespaces
> auth {TOKEN}
```

### Describe alternatives you've considered

https://kvrocks.apache.org/docs/namespace

**Comment by badrishc** [comment]
Why not just use different Garnet instances with different auth tokens?

**Comment by rnz** [comment]
@badrishc  > Why not just use different Garnet instances with different auth tokens?

Because cluster.

**Comment by rnz** [comment]
@TalZaccai why close? This is needed feature on cluster.

**Comment by TalZaccai** [comment]
Hi @rnz! We decided to close it as unplanned as this feature does not exist in comparable products either (e.g. Redis), so it's not prioritized on our roadmap. Thanks!

**Comment by rnz** [comment]
@TalZaccai this is the wrong decision! 
Redis has its own shortcomings. And ignoring things that are in demand in practice is unreasonable. 

Redis initially clearly lacks isolated access to data, but with Redis this problem is not acute, since rarely will someone place a large set of data on a single-threaded server. 
Therefore, in a Redis cluster, there is no way to use several databases in a cluster. And more often, they simply create several Redis clusters for different sets of data. The same applies to ACL - isolating access based on regular expressions is suitable only for a small amount of data.

However, Garnet, due to the effective use of multithreading and high performance, directly encourages its use on multi-processor servers, which usually have a lot of RAM and storage, and this in turn provokes the placement of more data. 
That is, a cluster on Garnet encourages the use of fewer servers, but with greater resources for CPU and RAM, if possible utilizing the entire server allocated for each node. This is reasonable based on TCO. 
In turn, the ability to place more data in a cluster automatically leads to the need to separate, isolate data sets and restrict access to them.  And namespaces are a completely reasonable solution for those cases in which the use of a garnet server is most justified.
