### ISSUE TITLE
Protocol RESP3 is not available in the latest version of Garnet.

### ISSUE THREAD

**Issue by kyuminMoon** [microsoft/garnet#420]
### Describe the bug

Protocol RESP3 was available in Garnet 1.0.8 and earlier versions, but when using the latest version, only connections using RESP2 are available.
We are currently developing using the Lettuce library, and the default protocol setting for that library is RESP3. I know that this protocol is supported since Redis 6.x version, and in fact, it worked without any problems in version 1.0.8.

I am leaving the modified code that works now for other users.
```
val configuration = RedisStandaloneConfiguration(host, port)
        val clientConfig = LettuceClientConfiguration.builder()
            .clientOptions(ClientOptions.builder().protocolVersion(ProtocolVersion.RESP2).build())
            .build()
        val lettuceConnectionFactory = LettuceConnectionFactory(configuration)
        lettuceConnectionFactory.afterPropertiesSet()
        return lettuceConnectionFactory
```

### Steps to reproduce the bug

val configuration = RedisStandaloneConfiguration(host, port)
        val lettuceConnectionFactory = LettuceConnectionFactory(configuration)
        lettuceConnectionFactory.afterPropertiesSet()
        return lettuceConnectionFactory

### Release version

v1.0.10

**Comment by badrishc** [comment]
Do you mean 1.0.10 or the latest on main which doesn't have a release version yet?

**Comment by badrishc** [comment]
Also, check and let me know if this PR fixes the problem with RESP3. Thanks for your assistance:

https://github.com/microsoft/garnet/pull/387

**Comment by kyuminMoon** [comment]
The version in question was the latest version of the docker image, and it was confirmed that the connection was established normally when using tag 1.0.10. 
The problem is occurring in the latest version of the main branch, which does not have a release version.

**Comment by kyuminMoon** [comment]
As a result of creating a docker image using the badrishc/async-resp branch of #387, the connection was successful. Thank you for checking.
