### ISSUE TITLE
Looking forward to supporting geo polygon queries.

### ISSUE THREAD

**Issue by bouyeijiang** [microsoft/garnet#424]
### Feature request type

sample request

### Is your feature request related to a problem? Please describe

Implement intersection,within,near, etc

### Describe the solution you'd like

Implement intersection,within,near, etc

**Comment by chunjieyaya** [comment]
This would be a great feature to have

**Comment by bouyeijiang** [comment]
谢谢您的来信！我会及时查阅的

**Comment by badrishc** [comment]
Is this a feature beyond the redis api? please provide exact details on expected API and semantics, with examples.

**Comment by bouyeijiang** [comment]
For example,Features rich geospatial data storage and querying supported by ES and mongodb
