### ISSUE TITLE
Unpin PoolEntry items in LimitedFixedBufferPool class?

### ISSUE THREAD

**Issue by AliKhalili** [microsoft/garnet#460]
### Describe the bug

I recently came across the `LimitedFixedBufferPool` class and noticed that its [`Dispose`](https://github.com/microsoft/garnet/blob/5916135b507087a7f3b83d35b4ed464b8695d468/libs/common/Memory/LimitedFixedBufferPool.cs#L107) method doesn't dispose of individual `PoolEntry` items after [dequeuing ](https://github.com/microsoft/garnet/blob/5916135b507087a7f3b83d35b4ed464b8695d468/libs/common/Memory/LimitedFixedBufferPool.cs#L126)them. This isn't a major issue, but if we're using handles to pin entry instances, it would be better to unpin these handles when disposing.
Is there a reason behind that?

### Steps to reproduce the bug

n/a

**Comment by vazois** [comment]
Thanks for bringing this too our attention. We are not currently using the handles option for the PoolEntry.
I created PR #465 to remove it all together to avoid any confusion and possible misuse in the future.
