### ISSUE TITLE
Add a unified prefix-key   by auth user/application in service side to enable multiple applications to share the same garnet service

### ISSUE THREAD

**Issue by springmin** [microsoft/garnet#470]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

Garrnet  is so high performence ,multiple applications sharing a garnet server is good idea to shudown cost,   

### Describe the solution you'd like

Extend configuration options and implement default prefixes and configure default prefixes  for each authenticated user according to rules based on authenticated users

**Comment by TalZaccai** [comment]
Duplicate of #415

**Comment by esafak** [comment]
@TalZaccai Was this completed as implemented? If so, what was the PR?
