### ISSUE TITLE
unexpected result in hgetall with RESP3

### ISSUE THREAD

**Issue by mperham** [microsoft/garnet#491]
### Describe the bug

I'm using Ruby's redis-client gem to connect to Garnet.

Redis is properly returning a Hash, whereas Garnet is unexpectedly returning an Array.

### Steps to reproduce the bug

```ruby
> gem install redis-client
> irb
require "redis-client"
c = RedisClient.new
c.call "hset", "foo", "bar", "mike"
c.call "hgetall", "foo"
{"bar"=>"mike"} # Redis 7.2.3
["bar", "mike"] # Garnet main
```

### Release version

main

**Comment by badrishc** [comment]
We are adding per-operator RESP3 support on an incremental and on-demand basis. Have covered ZRANGE in the linked PR.
