### ISSUE TITLE
unexpected result in ZRANGE with RESP3

### ISSUE THREAD

**Issue by mperham** [microsoft/garnet#492]
### Describe the bug

Notice also that Redis returns the scores as numeric, rather than strings.

### Steps to reproduce the bug

```ruby
require "redis-client"
c = RedisClient.new
c.call "zadd", "mike", "12.5", "bob"
c.call "zadd", "mike", "22.5", "bill"
c.call "zrange", "mike", "0", "300", "withscores"
```

Redis:
=> [["bob", 12.5], ["bill", 22.5]]
Garnet:
=> ["bob", "12.5", "bill", "22.5"]

### Release version

main

**Comment by badrishc** [comment]
We are adding per-operator RESP3 support on an incremental and on-demand basis. Have covered ZRANGE in the linked PR.
