### ISSUE TITLE
Lua support - EVAL and friends

### ISSUE THREAD

**Issue by mmclure-msft** [microsoft/garnet#509]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

Our team's code is heavily dependent on Redis and we're looking into the possible performance benefits of using Garnet. However, we're heavily dependent on the Redisson library which itself is a heavy user of Lua scripting with EVAL/EVALSHA, for example
https://github.com/redisson/redisson/blob/670c7dbdc0187801d55c8a457fe294cc9ce43020/redisson/src/main/java/org/redisson/RedissonMapCache.java#L535
As such, we can't replace Redis with Garnet until EVAL support is added.

### Describe the solution you'd like

Support for Lua scripting and the EVAL family of commands.

### Describe alternatives you've considered

Our only alternative would be to implement the functionality of Redisson as Garnet extensions. This would be a heavy lift.

### Additional context

I understand that adding Lua support will be a big feature request - I'm just opening the conversation to see if this is on the roadmap.

**Comment by mardukbp** [comment]
Celery, a popular Python library for background jobs also depends on EVALSHA.

**Comment by eve8110** [comment]
BullMQ, a popular library in Node.js, also relies on Lua scripts.

**Comment by mardukbp** [comment]
Awesome! Thanks @badrishc for implementing this. Unfortunately, it does not work as expected. Here is a minimal Python script that fails with `redis.exceptions.ResponseError: NOSCRIPT No matching script. Please use EVAL.`:

```python
import redis

lua = """
local value = redis.call('GET', KEYS[1])
value = tonumber(value)
return value * ARGV[1]
"""

r = redis.Redis()
multiply = r.register_script(lua)
r.set('foo', 2)
multiply(keys=['foo'], args=[5])
```

Actually I tested Garnet with Celery and I got the above error. So I searched for a minimal example to reproduce it.

**Comment by badrishc** [comment]
> Awesome! Thanks @badrishc for implementing this. Unfortunately, it does not work as expected. Here is a minimal Python script that fails with `redis.exceptions.ResponseError: NOSCRIPT No matching script. Please use EVAL.`:
> 
> ```python
> import redis
> 
> lua = """
> local value = redis.call('GET', KEYS[1])
> value = tonumber(value)
> return value * ARGV[1]
> """
> 
> r = redis.Redis()
> multiply = r.register_script(lua)
> r.set('foo', 2)
> multiply(keys=['foo'], args=[5])
> ```
> 
> Actually I tested Garnet with Celery and I got the above error. So I searched for a minimal example to reproduce it.

What language is your client code (redis.Redis() etc.) written in?

**Comment by badrishc** [comment]
> Awesome! Thanks @badrishc for implementing this. Unfortunately, it does not work as expected. Here is a minimal Python script that fails with `redis.exceptions.ResponseError: NOSCRIPT No matching script. Please use EVAL.`:
> 
> ```python
> import redis
> 
> lua = """
> local value = redis.call('GET', KEYS[1])
> value = tonumber(value)
> return value * ARGV[1]
> """
> 
> r = redis.Redis()
> multiply = r.register_script(lua)
> r.set('foo', 2)
> multiply(keys=['foo'], args=[5])
> ```
> 
> Actually I tested Garnet with Celery and I got the above error. So I searched for a minimal example to reproduce it.

Here is a fix that runs your repro correctly: https://github.com/microsoft/garnet/pull/600 - please try it out.

**Comment by mardukbp** [comment]
Now it works!
