### ISSUE TITLE
ZRANGE behaviour inconsistent with Redis with using REV

### ISSUE THREAD

**Issue by danielgerlag** [microsoft/garnet#515]
### Describe the bug

According to the Redis documentation on ZRANGE, when using the REV parameter with BYSCORE or BYLEX, the <start> and <stop> parameters are essentially switched.

Quote from https://redis.io/docs/latest/commands/zrange/
```
Using the REV option reverses the sorted set, with index 0 as the element with the highest score.

By default, <start> must be less than or equal to <stop> to return anything. However, if the BYSCORE, or BYLEX options are selected, the <start> is the highest score to consider, and <stop> is the lowest score to consider, therefore <start> must be greater than or equal to <stop> in order to return anything.

For example:

ZRANGE zset 5 10 REV
Will return the elements between index 5 and 10 in the reversed index.

ZRANGE zset 10 5 REV BYSCORE
Will return all elements with scores less than 10 and greater than 5.
```

This does not appear to be the case with Garnet, I can get different results on the same data when using Redis vs. Garnet

### Steps to reproduce the bug

```
ZADD key1 1 1
ZADD key1 2 2
ZRANGE key1 1 -inf BYSCORE REV LIMIT 0 1
```

### Expected behavior

With Redis, the final command returns `1) "1"`
With Garnet, it returns nothing.

**Comment by TalZaccai** [comment]
Thanks for spotting this! Posting a fix shortly :)
