### ISSUE TITLE
publish docker image to the hub

### ISSUE THREAD

**Issue by John0King** [microsoft/garnet#524]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

current try garnet in docker is a little bit ”annoying“ ， it require to get the source and build the docker image manually.

### Describe the solution you'd like

publish the offfical docker image to the registary

**Comment by badrishc** [comment]
you do not need to get souces and build images manually. Docker releases are available here: https://github.com/microsoft/garnet/pkgs/container/garnet
