### ISSUE TITLE
Bug: Container Failed To Start using volume mount and `--checkpointdir`, Access to the path [checkpointdir path] is denied

### ISSUE THREAD

**Issue by Alirexaa** [microsoft/garnet#536]
### Describe the bug

Running garnet container to persist data using volume mount and `--checkpointdir` failed.

### Steps to reproduce the bug

Just run following command:

```
docker run --mount source=garnetdata,target=/data  ghcr.io/microsoft/garnet:1.0  "--checkpointdir" "/data/checkpoint" "--recover" "--aof"
```

### Expected behavior

Container runs without any errors.

### Additional context

Container Logs:

```
   /_||___||_\      Garnet 1.0.15 64 bit; standalone mode
   '. \   / .'      Port: 6379
     '.\ /.'        https://aka.ms/GetGarnet
       '.'

Unable to initialize server due to exception: Access to the path '/data/checkpoint' is denied.
```

**Comment by yrajas** [comment]
Could you please add details on what is the issue in Garnet side? Or is it purely within docker mounting permissions setup?

**Comment by Alirexaa** [comment]
> Could you please add details on what is the issue in Garnet side? Or is it purely within docker mounting permissions setup?

It seems related to docker mounting permissions, Running the container using bind mount works but using volume mount failed to start.

**Comment by badrishc** [comment]
Feel free to open a PR here, if there is anything we need to change in the docker file or docs.

**Comment by akoken** [comment]
For security reasons, Garnet containers run as a [non-root user](https://github.com/microsoft/garnet/blob/main/Dockerfile#L36), which causes the access denied error when creating a folder in the container.

There are a couple of workarounds:

- **Permission Specific Folders:** We can give permissions to specific folders in Dockerfiles. However, if users need to specify any path as an argument, this might not work.
- **Remove Non-Root User from Dockerfiles:** Another approach is to remove the non-root user from the Dockerfiles. This allows the container to run with root privileges, but it does compromise security.

For users prioritizing security and who want a more secure container, can build the Docker image from the source with the required permissions and their preferred volumes.

**Comment by badrishc** [comment]
Security is more important, so we should retain the non-root user. However, we can open up the log/checkpoint directories to writing by the Garnet process. Specifically, we can run Garnet with `--logdir /data/logs` then both the larger-than-memory cache data and checkpoints will no in the above folder. (`--checkpointdir` defaults to `--logdir` if not specified).

**Comment by Alirexaa** [comment]
When is the garnet image release date including this?

**Comment by akoken** [comment]
> When is the garnet image release date including this?

```bash
docker pull ghcr.io/microsoft/garnet:latest
```

**Comment by Alirexaa** [comment]
> > When is the garnet image release date including this?
> 
> ```shell
> docker pull ghcr.io/microsoft/garnet:latest
> ```

Could you tag this as `1.0`?

**Comment by badrishc** [comment]
Done.

**Comment by Alirexaa** [comment]
> Done.

Thanks.

**Comment by Alirexaa** [comment]
Running garnet container to persist data using bind mount failed to start (in Linux host).
```
docker run --mount type=bind,source=/data,target=/data ghcr.io/microsoft/garnet:1.0.19  "--checkpointdir" "/data/checkpoint" "--recover" "--aof"
```

Container log

```
Unable to initialize server due to exception: Access to the path '/data/checkpoints/AOF' is denied.
```

cc @badrishc @akoken

**Comment by akoken** [comment]
@Alirexaa  I don't see a problem tbh. Please make sure that your local `data` folder is empty and specify full path using `pwd`command.

![image](https://github.com/user-attachments/assets/47f4288f-67d0-43af-aca1-4dc8d58cc2be)
