### ISSUE TITLE
`monitor` not working

### ISSUE THREAD

**Issue by mgravell** [microsoft/garnet#538]
### Describe the bug

The `monitor` command doesn't work; it *should* start reporting server commands from other connections, but currently it just seems to hang the connection without ever reporting anything. If it isn't implemented, it should probably report a `-ERR something` ?

### Expected behavior

(window 1)

```
➜ .\redis-cli.exe monitor
OK
```

(window 2)

```
➜ .\redis-cli.exe set foo bar
OK
```

(window 1, updated)

```
1722003049.957668 [0 127.0.0.1:53956] "set" "foo" "bar"
```

### Actual behavior

(window 1)

```
➜ .\redis-cli.exe monitor
```

(note no OK)

(window 2)

```
➜ .\redis-cli.exe set foo bar
OK
```

(window 1)

(no update)

**Comment by badrishc** [comment]
Yes, monitor is not supported due to its impact on critical paths. We should report the error message correctly, though, as the first fix here.

**Comment by mgravell** [comment]
👍 something as simple as `-ERR unknown command` (or something more specific) would IMO be preferable to the current state, which leaves the caller scratching their head

**Comment by TalZaccai** [comment]
Added PR to return unknown command error. Thanks for spotting!
