### ISSUE TITLE
Docker image is missing libaio1 so running Garnet with --use-native-device-linux does not work

### ISSUE THREAD

**Issue by shanipribadi** [microsoft/garnet#547]
### Describe the bug

Running garnet using the image generated from the Dockerfile with --use-native-device-linux fails with the following error
```
Unable to initialize server due to exception: Unable to load shared library 'runtimes/linux-x64/native/libnative_device.so' or one of its dependencies. In order to help diagnose loading
problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:   

libaio.so.1: cannot open shared object file: No such file or directory
```

### Steps to reproduce the bug

1. build image `podman build . -t local/garnet`
2. run garnet `podman run --rm local/garnet --use-native-device-linux -r --aof -l /data --storage-tier` 
3. get the above error

alternatively
1. `podman run --rm ghcr.io/microsoft/garnet:sha-1f7e6d3 --use-native-device-linux -r --aof -l /data --storage-tier`
2. get the above error

### Release version

commit dd31566ae8cf9c538ba08b739a416b2741ad08f8

### OS version

linux

### Additional context

The following patch fixes the issue by installing libaio1 in the image
```
diff --git a/Dockerfile b/Dockerfile
index f69bd103..898a7629 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,3 +1,6 @@
+FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
+RUN apt-get update && apt-get install -y libaio1 && apt-get clean && rm -rf /var/lib/apt/lists/*
+
 FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
 ARG TARGETARCH
 WORKDIR /src
@@ -28,7 +31,7 @@ WORKDIR /src/main/GarnetServer
 RUN dotnet publish -a $TARGETARCH -c Release -o /app --no-restore --self-contained false -f net8.0

 # Final stage/image
-FROM mcr.microsoft.com/dotnet/runtime:8.0 AS runtime
+FROM runtime
 WORKDIR /app
 COPY --from=build /app .            
```

**Comment by TalZaccai** [comment]
Thanks for raising this! This has been fixed for all Linux images except chiseled (for which the Linux native flag remains unsupported at the moment)
