### ISSUE TITLE
Will future support vector storage be available？

### ISSUE THREAD

**Issue by snake-L** [microsoft/garnet#55]
Good evening, would you like to ask if Garnet has any plans for support vector storage in the future? Like Redis, it feels amazing!

**Comment by yrajas** [comment]
Current roadmap is available here https://microsoft.github.io/garnet/docs/welcome/roadmap
We are always striving to increase the API compatibility.
Appreciate community contributions as well!

**Comment by Sahilthakr** [comment]
In 2023Q3, there was a significant shift in the landscape of large language models (LLMs), as vector databases began to serve as external memory for these models. This innovative approach marked the inception of what would later be termed Retrieval-Augmented Generation (RAG). By utilizing vector databases as external memory, LLMs gained access to vast repositories of knowledge and information, enhancing their capabilities in understanding and generating text.

Throughout 2023Q4, the concept of RAG gained momentum and recognition within the AI and natural language processing communities. Researchers and practitioners alike recognized the potential of this approach to revolutionize various applications, including information retrieval, question answering, and text generation. As more studies showcased the effectiveness of RAG in improving model performance and generating more contextually relevant responses, it began to garner widespread attention and acclaim.

By the end of 2023, many experts and commentators were speculating that 2024 would be the "Year of RAG." The anticipation stemmed from the growing adoption of RAG across industries, coupled with the continuous advancements in both vector database technology and large language models. With RAG poised to reshape how AI systems interact with and understand textual data, the stage was set for a transformative year ahead in the field of natural language processing.
