### ISSUE TITLE
[helm-chart] Please provide a package for the helm chart for each release

### ISSUE THREAD

**Issue by babykart** [microsoft/garnet#554]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

Could you provide the generation of a helm chart package for each release.
This would facilitate the use and adoption of garnet in kubernetes.
Of course with a mention in the documentation would also be welcome.

### Describe the solution you'd like

The package generation could be done using github workflows such as https://github.com/helm/chart-releaser-action

**Comment by babykart** [comment]
There is an issue for more documentation on container usage #313

**Comment by badrishc** [comment]
Please feel free to continue submitting PRs in this space. We are depending on community users who need Helm charts to help us maintain it. Thanks for your contributions!
