### ISSUE TITLE
Is there by any chance support for DAPR?

### ISSUE THREAD

**Issue by nikneem** [microsoft/garnet#56]
Hi,
I ran into this project and I'm really curious. I want to go ahead and try Garnet as an alternative to Redis. However, my projects at this time are configured to use DAPR. The State Store for DAPR is configured to use Redis as an underlying storage mechanism. Can I easily swap Redis out with Garnet?

**Comment by yrajas** [comment]
Though it has not been explicitly tested with DAPR, going by the documentation here https://docs.dapr.io/reference/components-reference/supported-state-stores/setup-redis/ it should be possible to integrate it with DAPR for the basic state store functionality. 
However, the optional querying JSON objects requires modules like redisearch and redisjon which are currently not supported.
Please feel free to give it a try and raise issues if you see any incompatibility.
