### ISSUE TITLE
Use generic host for GarnetServer

### ISSUE THREAD

**Issue by Meir017** [microsoft/garnet#579]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

Using the generic host https://learn.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host will simplify how we bootstrap the server

### Describe the solution you'd like

wire up using [DI](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection) the dependencies that are created manually.

### Additional context

see the manual configuration https://github.com/microsoft/garnet/blob/main/libs/host/GarnetServer.cs#L151C13-L210C57

**Comment by badrishc** [comment]
Mostly addressed by https://github.com/microsoft/garnet/pull/614 - feel free to create PR if you have more ideas in this space.
