### ISSUE TITLE
Unable to initialize server due to exception: Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by mullvaden** [microsoft/garnet#58]
Hi!
I can run a console app locally (Windows) fine, Just the three lines in Program.cs:
```
            using var server = new Garnet.GarnetServer(["--port", "8080"]);
            server.Start();
            Thread.Sleep(Timeout.Infinite);
```
But when packaging this console app and running it in kubernetes (using alpine, net8 as base) I get 

> Unable to initialize server due to exception: Exception of type 'System.OutOfMemoryException' was thrown.

The pod has 2 GB memory, which should be more than sufficient. And I can see from monitoring that the pod hardly uses any memory at all.

Any guidance on how to proceed?

**Comment by badrishc** [comment]
The default index size is huge (8GB) so please run it with a smaller index size by adding the parameter: "-i", "128m". Also memory size default is 16GB, so perhaps make it "-m", "1g".

Defaults are here: https://github.com/microsoft/garnet/blob/main/libs/host/defaults.conf

**Comment by mullvaden** [comment]
That worked just fine, thanks!
