### ISSUE TITLE
API: CLIENT LIST

### ISSUE THREAD

**Issue by benh57** [microsoft/garnet#603]
### Feature request type

enhancement

### Is your feature request related to a problem? Please describe

We use the 'CLIENT LIST' Redis api, and would like to use this with Garnet

### Describe the solution you'd like

'CLIENT LIST' functionality, with the same response as Redis

### Additional context

Would it be possible to implement CLIENT LIST?  It might be something we could tackle if provided some guidance as to where it would be added.

**Comment by plucked** [comment]
Regarding how to do it, there is a great documentation about it here: https://microsoft.github.io/garnet/docs/dev/onboarding

**Comment by TalZaccai** [comment]
Hi @benh57! We have docs dedicated to how to add a command to the Garnet API [here](https://microsoft.github.io/garnet/docs/dev/garnet-api). Let me know if you need anything else! Thanks for willing to contribute!

**Comment by MojtabaTajik** [comment]
Where do we store the client's info? I can't find the storage object where clients' info is stored.

**Comment by benh57** [comment]
Thanks for the pointers. I've started experimenting with adding some commands on my fork.

**Comment by Vijay-Nirmal** [comment]
@TalZaccai This can be closed as its already implemented as part of #620

**Comment by benh57** [comment]
Glad to see this. I did start some work on my own but didn't get very far, looks like a much better implementation was put in. Thanks!
