### ISSUE TITLE
OOM Exceptions on heavy Usage

### ISSUE THREAD

**Issue by hr-alebel** [microsoft/garnet#610]
### Describe the bug

We tried using Garnet in our systems and encountered a unexpected behaviour.

Our usage consist of writing and reading a lot of keys with TTLs. The TTLs never get renewed, but are let to be expired in which case new keys are written (the keys have timestamps in them).

The value sizes are from some bytes up to almost 100MB per key.

We only use the String objects so object store is disabled.

When running the system under load it starts to use incresingly more RAM, up to the point that it OOMs due to Kubernetes Memory Limits.

There isnt much in the logs besides an endless stream of OOM Exceptions

Parameters are "--memory=1g", "--index=1g", "--page=512m", "--no-obj=true", "--metrics-sampling-freq=1"
Garnet uses over 3.5GB in those cases.

As reference we switched to Redis in the same application, the max storage required was around 300MB, with no OOM issues what so ever.

### Steps to reproduce the bug

1. Have garnet running
2. Cyclically write a lot of keys of variable sizes with TTLs
3. on expiration of keys, write new ones of aproximately the same size
4. See Memory rise
5. wait for Garnet to OOM

### Expected behavior

Garnet should reuse the memory pages it has when keys expire or have a way of compacting its memory so a high TTL-Key rate does not lead to a memory leak.

### Release version

1.0.18

### OS version

K8s

**Comment by TedHartMS** [comment]
Thanks for the report. I don't know why an OOM happens in this case. Do you have a repro client app you can include here?

**Comment by badrishc** [comment]
Ping

**Comment by msft-paddy14** [comment]
@hr-alebel along with OOM allocating stack. It would be good to know the container memory provisioned for the Pod. Have you configured  - DOTNET_GCHeapHardLimitPercent? The default value is 75% which means you need to add some overhead or increase this value

**Comment by hr-alebel** [comment]
@msft-paddy14 the provisioned memory was around 3.7GB
The data stored is around  300MB max (also thats around the size of memory redis uses now)

@TedHartMS Sry for the late response. I had some stress fixing other stuff too, will try to make a app that repliactes the issue today

**Comment by hr-alebel** [comment]
@TedHartMS https://github.com/hr-alebel/GarnetOOMIssue
I created a small repo. it isnt the most beutiful one, but it gets the job done for me. let it run for a bit and see the memory rise.

Garnet ran in docker desktop using ```docker run --name garnet-service  -p 6379:6379 ghcr.io/microsoft/garnet --page=512m --memory=1g --index=1g --no-obj=true --metrics-sampling-freq=1```

**Comment by hr-alebel** [comment]
I think the issue might not actually be the writing, but reading. Will do some more tests right now and update the repo

**Comment by hr-alebel** [comment]
Updated the repo with using "MEMORY USAGE", this basically instantly OOM garnet. Not sure if some part of our software uses that, its a giant PHP Symfony project and there is a lot of blackbox behaviour, but regardless, getting the size of keys shouldnt lead to OOM exceptions.

**Comment by Degot** [comment]
FYI: I tried to reproduce issue. It took 50 seconds till Exception. Garnet took 3.2GB. Exception message:
```
ProcessMessages threw an exception: 
    System.OverflowException: 
        Arithmetic operation resulted in an overflow.    
        at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, GC_ALLOC_FLAGS flags)    
        at System.GC.AllocateArray[T](Int32 length, Boolean pinned)    
        at Garnet.server.ScratchBufferManager.ExpandScratchBuffer(Int32 newLength)    
        at Garnet.server.ScratchBufferManager.FormatScratch(Int32 headerSize, ReadOnlySpan`1 arg)    
        at Garnet.server.StorageSession.GET[TContext](ArgSlice key, ArgSlice& value, TContext& context)    
        at Garnet.server.StorageSession.MemoryUsageForKey[TContext,TObjectContext](ArgSlice key, Int64& memoryUsage, TContext& context, TObjectContext& objectContext, Int32 samples)    
        at Garnet.server.GarnetApi`2.MemoryUsageForKey(ArgSlice key, Int64& memoryUsage, Int32 samples)    at Garnet.server.RespServerSession.NetworkMemoryUsage[TGarnetApi](TGarnetApi& storageApi)    
        at Garnet.server.RespServerSession.ProcessMessages()    
        at Garnet.server.RespServerSession.TryConsumeMessages(Byte* reqBuffer, Int32 bytesReceived)
```

**Comment by TheMasterofBlubb** [comment]
> I've disabled **MEMORY USAGE** loop and no Exceptions after 5 mins. GarnetServer memory usage MAX 1.3GB.

Considering the max Stored Data is ~300MB thats still a lot of overhead, but at least not as critical.
