### ISSUE TITLE
Registration for Garnet service failed to start

### ISSUE THREAD

**Issue by xiazhao001** [microsoft/garnet#616]
### Describe the bug

After registering the Windows service with Garnet, it failed to start and prompted a timeout (30000 milliseconds) for waiting for the connection to the GarnetService service.

### Steps to reproduce the bug

![Uploading image.png…]()
![Uploading image.png…]()

**Comment by TalZaccai** [comment]
This isn't currently supported in main, in the meantime you can check out this PR - https://github.com/microsoft/garnet/pull/614
