### ISSUE TITLE
recover  from AOF   lose  `TTL`

### ISSUE THREAD

**Issue by John0King** [microsoft/garnet#647]
### Describe the bug

I use follow command to start the docker image  
```pwsh
docker run --name MS-Garnet -p 6378:6379  ghcr.io/microsoft/garnet  --aof true --logger-level trace --recover true
```

then I notice that when I stop the container,   and restart the conatiner , the data   preserved ，  but it lose the TTL infomation

### Steps to reproduce the bug

1.  start docker with above command
2.  create a key with TTL  120  seconds
3.  before the key expire,  stop the container  and restart the container
4.  checkout the key and see it's TTL infomation

### Expected behavior

the key has the TTL , or the is been deleted because the TTL expired

### Release version

 Garnet 1.0.19 64 bit; standalone mode

**Comment by TalZaccai** [comment]
I can't seem to reproduce the behavior you are describing. Are you sure the AOF got committed?
Here's what I did:

Server (Enable AOF & commit after each command):
```
GarnetServer.exe --aof --aof-commit-freq 0
```

Client:
```
127.0.0.1:6379> set key1 val123 ex 600
OK
127.0.0.1:6379> ttl key1
(integer) 594
```

*kill server & client*

Server (Enable AOF and recover):
```
GarnetServer.exe --aof -r
```

Client:
```
127.0.0.1:3278> get key1
"val1234"
127.0.0.1:3278> ttl key1
(integer) 578
```

**Comment by John0King** [comment]
I  pull the latest docker image today ,  and  now it worked

**Comment by akoken** [comment]
@John0King 

When you run `docker run` command, container has a temporary filesystem based on linux distro in the base image. It's destroyed when you kill the container. If you want to use AOF, you should be using docker volume to persist container data. The following should work in your case:

```bash
docker run -v garnet-data:/data ghcr.io/microsoft/garnet:1.0.19  "--checkpointdir" "/data/checkpoint" "--recover" "--aof"
```

**Comment by John0King** [comment]
@akoken   since the docker image already using a volume ,  should  the `checkpoindir`  set to the volumn mounted folder by default (eg.  set the `DOTNET_checkpoindir` envrioment variable in docker file)?

**Comment by akoken** [comment]
@John0King  Yes, I agree. It should default to the /data folder. However, there’s always a risk if the user places it outside the /data folder and forgets to mount it as a volume. It may also be worthwhile to improve the Docker section in the documentation. Given that persistency is key in most use cases, the Docker examples should use volumes by default.

**Comment by badrishc** [comment]
Closing as workaround provided. We cannot use that as default in the command line of Docker, as the garnet.conf might have some user-desired subdirectory, and we do not want to enforce this /data.
