### ISSUE TITLE
Map deprecated Redis comments to its alternative if its already exist in Garnet

### ISSUE THREAD

**Issue by Vijay-Nirmal** [microsoft/garnet#684]
### Feature request type

sample request

### Is your feature request related to a problem? Please describe

Personally, I don't like to waste our time in implementing deprecated commands. But the issue is that these deprecated Redis comments will not be removed for years before they are removed completely. This means libraries and applications could still continue to use it even it's not recommented.

### Describe the solution you'd like

I like to map deprecated comments to its alternative if it's already exist in Garnet

### Additional context

I can raise the PR for this if the garnet team is fine with this change.

**List of all deprecated comments and their status on where are supported in Garnet**
- [x] GEORADIUS_RO 
- [x] GEORADIUSBYMEMBER_RO 
- [x] SETEX 
- [x] QUIT 
- [x] SUBSTR 
- [ ] BRPOPLPUSH
- [x] GEORADIUSBYMEMBER 
- [x] HMSET
- [x] PSETEX 
- [x] ZREVRANGE 
- [x] GEORADIUS 
- [x] ZRANGEBYLEX
- [x] GETSET
- [x] RPOPLPUSH
- [ ] ZREVRANGEBYLEX
- [x] ZREVRANGEBYSCORE
- [x] CLUSTER SLAVES
- [x] SLAVEOF
- [x] ZRANGEBYSCORE
- [x] CLUSTER SLOTS
- [x] SETNX

**Comment by yrajas** [comment]
Good point. Thanks.
Please open a PR for this.

**Comment by Vijay-Nirmal** [comment]
@yrajas Should the deprecated command need to be added as part of `IGarnetApi` or can it be mapped to the alternative in the network layer (RespServerSession) itself?
