### ISSUE TITLE
Bug cluster create

### ISSUE THREAD

**Issue by KerimNar** [microsoft/garnet#768]
### Describe the bug

2024-11-02T12:57:59.653318774+05:00 07::57::59 fail: ClusterManager[0] Meet terminated with error System.FormatException: An invalid IP address was specified.  ---> System.Net.Sockets.SocketException (22): Invalid argument    --- End of inner exception stack trace ---    at System.Net.IPAddressParser.Parse(ReadOnlySpan`1 ipSpan, Boolean tryParse)    at Garnet.client.GarnetClient.GetSendSocket(Int32 millisecondsTimeout) in /src/libs/client/GarnetClient.cs:line 254    at Garnet.client.GarnetClient.ConnectAsync(CancellationToken token) in /src/libs/client/GarnetClient.cs:line 224    at Garnet.client.GarnetClient.ReconnectAsync(CancellationToken token) in /src/libs/client/GarnetClient.cs:line 348    at Garnet.cluster.GarnetServerNode.Initialize() in /src/libs/cluster/Server/GarnetServerNode.cs:line 97    at Garnet.cluster.ClusterManager.Meet(String address, Int32 port) in /src/libs/cluster/Server/Gossip.cs:line 266

### Steps to reproduce the bug

redis-cli -h garnet-group1-0.garnet-group1-headless.garnet.svc.cluster.local --cluster create \
garnet-group1-0.garnet-group1-headless.garnet.svc.cluster.local:6379 \
garnet-group2-0.garnet-group2-headless.garnet.svc.cluster.local:6379 \
garnet-group3-0.garnet-group3-headless.garnet.svc.cluster.local:6379 \
garnet-group1-1.garnet-group1-headless.garnet.svc.cluster.local:6379 \
garnet-group2-1.garnet-group2-headless.garnet.svc.cluster.local:6379 \
garnet-group3-1.garnet-group3-headless.garnet.svc.cluster.local:6379 \
--cluster-replicas 1

### Expected behavior

M: 2368e283ef4eaf07e2705c292166474c65f22ce5 garnet-group1-0.garnet-group1-headless.garnet.svc.cluster.local:6379
   slots:[0-5460] (5461 slots) master
M: 28e6912d9a8c14130901f095ab17fae3a55c945c garnet-group2-0.garnet-group2-headless.garnet.svc.cluster.local:6379
   slots:[5461-10922] (5462 slots) master
M: 48c12215afc0fb1a7c4f1200408959244b461ee7 garnet-group3-0.garnet-group3-headless.garnet.svc.cluster.local:6379
   slots:[10923-16383] (5461 slots) master
S: 8883597eff50b19990284a512a22b676d9a7416f garnet-group1-1.garnet-group1-headless.garnet.svc.cluster.local:6379
   replicates 48c12215afc0fb1a7c4f1200408959244b461ee7
S: 31cc1573856f1c97eaef04855a04cc339eb37b75 garnet-group2-1.garnet-group2-headless.garnet.svc.cluster.local:6379
   replicates 2368e283ef4eaf07e2705c292166474c65f22ce5
S: da62efcf3a5db3c1def00ec42c78be5bd3cbf928 garnet-group3-1.garnet-group3-headless.garnet.svc.cluster.local:6379
   replicates 28e6912d9a8c14130901f095ab17fae3a55c945c

**Comment by vazois** [comment]
Can you please check if the above PR fixes your issue? Thanks!

**Comment by KerimNar** [comment]
> Can you please check if the above PR fixes your issue? Thanks!

Yes. Thank you!


redis-cli -h garnet-master1-0.garnet-master1-headless.garnet.svc.cluster.local --cluster create \
garnet-master1-0.garnet-master1-headless.garnet.svc.cluster.local:6379 \
garnet-master2-0.garnet-master2-headless.garnet.svc.cluster.local:6379 \
garnet-master3-0.garnet-master3-headless.garnet.svc.cluster.local:6379 \
garnet-slave1-0.garnet-slave1-headless.garnet.svc.cluster.local:6379 \
garnet-slave2-0.garnet-slave2-headless.garnet.svc.cluster.local:6379 \
garnet-slave3-0.garnet-slave3-headless.garnet.svc.cluster.local:6379 \
--cluster-replicas 1
>>> Performing hash slots allocation on 6 nodes...
Master[0] -> Slots 0 - 5460
Master[1] -> Slots 5461 - 10922
Master[2] -> Slots 10923 - 16383
Adding replica garnet-slave2-0.garnet-slave2-headless.garnet.svc.cluster.local:6379 to garnet-master1-0.garnet-master1-headless.garnet.svc.cluster.local:6379
Adding replica garnet-slave3-0.garnet-slave3-headless.garnet.svc.cluster.local:6379 to garnet-master2-0.garnet-master2-headless.garnet.svc.cluster.local:6379
Adding replica garnet-slave1-0.garnet-slave1-headless.garnet.svc.cluster.local:6379 to garnet-master3-0.garnet-master3-headless.garnet.svc.cluster.local:6379
M: 257ce632248ad0ebefedb3ef4de61eb83adac5ef garnet-master1-0.garnet-master1-headless.garnet.svc.cluster.local:6379
   slots:[0-5460] (5461 slots) master
M: 692b666c0e5a81c8f151d879a3bc99e5f2fdf6a5 garnet-master2-0.garnet-master2-headless.garnet.svc.cluster.local:6379
   slots:[5461-10922] (5462 slots) master
M: 57bcc368f165d75b9f93099d44ad4efc61273f5c garnet-master3-0.garnet-master3-headless.garnet.svc.cluster.local:6379
   slots:[10923-16383] (5461 slots) master
S: 124b8a438e6c800618d14ddb4da0d249669cbb9d garnet-slave1-0.garnet-slave1-headless.garnet.svc.cluster.local:6379
   replicates 57bcc368f165d75b9f93099d44ad4efc61273f5c
S: 7585d9750fce1af956da8265b2c06561b4c7377c garnet-slave2-0.garnet-slave2-headless.garnet.svc.cluster.local:6379
   replicates 257ce632248ad0ebefedb3ef4de61eb83adac5ef
S: cf3d5c1330bd54db40ed1845aa6484bc26c21fa7 garnet-slave3-0.garnet-slave3-headless.garnet.svc.cluster.local:6379
   replicates 692b666c0e5a81c8f151d879a3bc99e5f2fdf6a5
Can I set the above configuration? (type 'yes' to accept): yes
>>> Nodes configuration updated
>>> Assign a different config epoch to each node
>>> Sending CLUSTER MEET messages to join the cluster
Waiting for the cluster to join
.
>>> Performing Cluster Check (using node garnet-master1-0.garnet-master1-headless.garnet.svc.cluster.local:6379)
M: 257ce632248ad0ebefedb3ef4de61eb83adac5ef garnet-master1-0.garnet-master1-headless.garnet.svc.cluster.local:6379
   slots:[0-5460] (5461 slots) master
   1 additional replica(s)
S: cf3d5c1330bd54db40ed1845aa6484bc26c21fa7 10.251.35.118:6379
   slots: (0 slots) slave
   replicates 692b666c0e5a81c8f151d879a3bc99e5f2fdf6a5
S: 124b8a438e6c800618d14ddb4da0d249669cbb9d 10.251.156.130:6379
   slots: (0 slots) slave
   replicates 57bcc368f165d75b9f93099d44ad4efc61273f5c
S: 7585d9750fce1af956da8265b2c06561b4c7377c 10.251.75.119:6379
   slots: (0 slots) slave
   replicates 257ce632248ad0ebefedb3ef4de61eb83adac5ef
M: 57bcc368f165d75b9f93099d44ad4efc61273f5c 10.251.35.117:6379
   slots:[10923-16383] (5461 slots) master
   1 additional replica(s)
M: 692b666c0e5a81c8f151d879a3bc99e5f2fdf6a5 10.251.75.118:6379
   slots:[5461-10922] (5462 slots) master
   1 additional replica(s)
[OK] All nodes agree about slots configuration.
>>> Check for open slots...
>>> Check slots coverage...
[OK] All 16384 slots covered.
