### ISSUE TITLE
API Coverage - Implement ZMSCORE

### ISSUE THREAD

**Issue by TalZaccai** [microsoft/garnet#77]
Here's your opportunity to implement a RESP command in Garnet! 

**Syntax:** 
`ZMSCORE key member [member ...]`

**Command description:**
Returns the scores associated with the specified `members` in the sorted set stored at `key`.

For every `member` that does not exist in the sorted set, a nil value is returned.

**Response:**
One of the following:

_Nil reply:_ if the member does not exist in the sorted set.
_Array reply:_ a list of string `member` scores as double-precision floating point numbers.

---

**How to approach this task:**
1. Add the new command info to the sortedSetCommandsInfoMap in the RespCommandsInfo class _(Garnet.server/Resp/RespCommandsInfo.cs)_
2. Add the new command string to the returned HashSet in the RespInfo.GetCommands method _(Garnet.server/Resp/RespInfo.cs)_
3. Add the appropriate fast parsing logic for the new command in the RespCommand.FastParseArrayCommand method (use other commands as reference) _(Garnet.server/Resp/RespCommand.cs)_
4. Implement the wrapper method to the storage layer in StorageSession _(Garnet.server/Storage/Session/ObjectStore/SortedSetOps.cs)_
5. Define a new method in IGarnetAPI and implement it in GarnetApiObjectCommands, calling the method you have implemented in step #4 _(Garnet.server/API/IGarnetAPI.cs, Garnet.server/API/GarnetApiObjectCommands.cs)_
6. Add a new method to the RespServerSession class which will call the storage API and return the appropriate response _(Garnet.server/Resp/Objects/SortedSetCommands.cs)_
8. Add a new method to SortedSetObjImpl which will perform the required operation on the hash object _(Garnet.server/Objects/SortedSet/SortedSetObjectImpl.cs)_
9. Add a new enum value to SortedSetOperation and add the appropriate case to the switch in SortedSetObject.Operate, in which you will call the method defined in step #8 _(Garnet.server/Objects/SortedSet/SortedSetObject.cs)_
10. Add an appropriate case to the switch in TransactionManager.SortedSetObjectKeys (Garnet.server/Transaction/TxnKeyManager.cs)
11. Add tests for the new command in the RespSortedSetTests class _(Garnet.test/RespSortedSetTests.cs)_

**Tip:** First add a simple test that calls the new command and use it to debug as you develop, it will make your life much easier!

If you have any questions, the Garnet team is here to help!

**Comment by Zzhiter** [comment]
I can help, can you assign this issue to me please? Thanks😊

**Comment by tisilent** [comment]
I want to give it a try. 👻

**Comment by darrenge** [comment]
Great!  Thanks for your help! Let us know if you have any questions :)

**Comment by tisilent** [comment]
wow
