### ISSUE TITLE
SET EX NX does not set a string longer than expired

### ISSUE THREAD

**Issue by nightroman** [microsoft/garnet#771]
### Describe the bug

`SET EX NX` does not set a string longer than expired, e.g. if the expired
string is "short" (length 5) and the new value is "longer" (length 6) then
the result is `true` as expected ~ the string is set, but the new string is
not actually stored, the key does not exist.

### Steps to reproduce the bug

```csharp
    [Fact]
    public void ExistingExpired6379()
    {
        var redis = ConnectionMultiplexer.Connect("127.0.0.1:6379,SyncTimeout=999999");
        var db = redis.GetDatabase();

        var key = "test:lock1";
        var value1 = "short";
        var value2 = "longer";
        var ttl1 = TimeSpan.FromMilliseconds(200);
        var ttl2 = TimeSpan.FromMinutes(1);

        // set expiring string "short" and let it expire
        db.StringSet(key, value1, ttl1);
        Thread.Sleep(ttl1 * 2);

        // set expiring string "longer" over expired "short" -> true ~ expected
        bool ok = db.StringSet(key, value2, ttl2, When.NotExists);
        Assert.True(ok);

        // but the expected string does not exist, null is returned, assert fails
        string? str = db.StringGet(key);
        Assert.Equal(value2, str);
    }
```

### Expected behavior

The above xunit test is supposed to pass (new string exists) but it fails (the string does not exist, although the operation returned `true`).

Note that the test passes is we use a shorter string as `value2`, e.g. "longe" instead of "longer".

### Release version

1.0.35

### IDE

Microsoft Visual Studio Community 2022 (64-bit) - 17.11.5

### OS version

Windows 11

**Comment by Vijay-Nirmal** [comment]
Raise a PR to fix it #772
