### ISSUE TITLE
Conflict with Spring Data Redis with spring boot 3.3

### ISSUE THREAD

**Issue by yuseok-kim-edushare** [microsoft/garnet#811]
### Describe the bug

When I use Garnet to replace Redis
My app written in Java with Spring Boot 3.3 and Spring Data Redis

I tried to test on container side and
Redis CLI works well in PING command
also Application's Execution of Ping works well

but Spring Application Try to connect Garnet, Fail to connect

and I checked logs, and finally found, when using Hello, fault on 

### Steps to reproduce the bug

1. create app with some Spring boot app with using Spring Data Redis, will trying to connect garnet
2. run garnet on docker container and run spring app
3. look fail message from spring boot's failure to application run

### Expected behavior

working well

### Screenshots

no prepared

### Release version

v1.0.36

### OS version

Ubuntu 24.04 LTS Host
running on docker compose (garnet latest, eclipse-temurin:21-jre

### Additional context

we operate garnet with out username and password, cause in docker network will ensure prevent to connect from external's

[failed codes](https://github.com/Prompt-oven/auth-service/blob/c87e39e7f93da52114dbb9f32d4c1d58db62deca/src/main/java/com/promptoven/authservice/adaptor/infrastructure/redis/RedisConfig.java)

[successed code](https://github.com/Prompt-oven/auth-service/blob/main/src/main/java/com/promptoven/authservice/adaptor/infrastructure/redis/RedisConfig.java)

**Comment by badrishc** [comment]
Can you perform the following steps?

* Uncomment these two lines in RespServerSession.cs: 
    * https://github.com/microsoft/garnet/blob/main/libs/server/Resp/RespServerSession.cs#L1060
    * https://github.com/microsoft/garnet/blob/main/libs/server/Resp/RespServerSession.cs#L392
* Build and run GarnetServer with argument: `--logger-level Trace`
* Run the client until it errors out
* Copy and paste the server-side verbose logs here

**Comment by yuseok-kim-edushare** [comment]
![Image](https://github.com/user-attachments/assets/17359761-3353-47c9-9cd6-3bf7b9a421fe)

01::48::45 dbug: GarnetServer[0] Accepted TCP connection from 127.0.0.1:51061
01::48::45 dbug: Session[0] [127.0.0.1:51061] [03FB24F0] Starting RespServerSession Id=1
01::48::45 trce: Session[0] [127.0.0.1:51061] [03FB24F0] RECV: [*2|$5|HELLO|$1|3|]
RECV: [*2|$5|HELLO|$1|3|]
01::48::45 SEND: [%8|$6|server|$5|redis|$7|version|$5|7.2.5|$14|garnet_version|$6|1.0.39|$5|proto|$1|3|$2|id|$2|63|$4|mode|$10|standalone|$4|role|$6|master|$7|modules|*0|]
trce: Session[0] [127.0.0.1:51061] [03FB24F0] SEND: [%8|$6|server|$5|redis|$7|version|$5|7.2.5|$14|garnet_version|$6|1.0.39|$5|proto|$1|3|$2|id|$2|63|$4|mode|$10|standalone|$4|role|$6|master|$7|modules|*0|]
01::48::50 dbug: Session[0] [127.0.0.1:51061] [03FB24F0] Disposing RespServerSession Id=1

**Comment by yuseok-kim-edushare** [comment]
@badrishc
 I add on Garnet Server Log

and if you need, you can see [Spring Data's Log](https://github.com/Prompt-oven/auth-service/issues/16#issue-2678014663)

**Comment by yuseok-kim-edushare** [comment]
Very works well with when client mode in RESP v2

![Image](https://github.com/user-attachments/assets/164e5c39-b620-4685-a2d3-ad098f735eb0)


01::59::34 dbug: GarnetServer[0] Accepted TCP connection from 127.0.0.1:59418
01::59::34 RECV: [*1|$4|PING|]
SEND: [+PONG|]
dbug: Session[0] [127.0.0.1:59418] [00A45263] Starting RespServerSession Id=3
01::59::34 trce: Session[0] [127.0.0.1:59418] [00A45263] RECV: [*1|$4|PING|]
01::59::34 trce: Session[0] [127.0.0.1:59418] [00A45263] SEND: [+PONG|]
01::59::34 RECV: [*2|$9|SUBSCRIBE|$24|settlement-first-created|]
trce: Session[0] [127.0.0.1:59418] [00A45263] RECV: [*2|$9|SUBSCRIBE|$24|settlement-first-created|]
01::59::34 SEND: [*3|$9|subscribe|$24|settlement-first-created|:1|]
trce: Session[0] [127.0.0.1:59418] [00A45263] SEND: [*3|$9|subscribe|$24|settlement-first-created|:1|]
01::59::34 RECV: [*1|$4|INFO|]
trce: Session[0] [127.0.0.1:59412] [003942B8] RECV: [*1|$4|INFO|]

**Comment by yuseok-kim-edushare** [comment]
I found that Lattuce (Java Client for Redis) has problem.

https://github.com/Prompt-oven/auth-service/issues/16#issuecomment-2490101447

**Comment by badrishc** [comment]
I don't see any issues on server side Garnet logs for both resp2 and resp3. Lmk if you see anything amiss

**Comment by yuseok-kim-edushare** [comment]
> I don't see any issues on server side Garnet logs for both resp2 and resp3. Lmk if you see anything amiss

Yes, You right.
Garnet Is Clear

I will find anwer from Spring and
**if some garnet need add docs for Java Spring Developer(like me) Maybe I will opne PR to update Docs**

Thank you for your kindness Answer and support @badrishc

**Comment by mp911de** [comment]
Lettuce 6.4 (or 6.5.) switches to fire-and-forget mode for these commands (IIRC).

**Comment by yuseok-kim-edushare** [comment]
@mp911de Still problem agian
I think in Present garent didn't support Client_SETINFO command  [Ref](https://microsoft.github.io/garnet/docs/commands/api-compatibility)
thus, need to make Client_SETINFO could be possible in Garnet to be more compatible with other RESP3 based Redis Clients

**Comment by yuseok-kim-edushare** [comment]
Ah, this way works
Dispite Client Setinfo didn't works, 
![Image](https://github.com/user-attachments/assets/732af152-026f-46a9-88a4-6da3ffde0e93)
