### ISSUE TITLE
Microsoft.Garnet package: Server Initialization Fails with just --help, missing log message

### ISSUE THREAD

**Issue by zachrybaker** [microsoft/garnet#817]
### Describe the bug

only some options seem to boot.  --port for example.  But specifying others fails, in a not-helpful way. 

--help, for example, will show you the help options, then crash in the constructor.  It will show:
07::09::39 info: ArgParser[0] Configuration import from embedded resource succeeded. Path: defaults.conf.
Unhandled exception. Garnet.common.GarnetException: Encountered an error when initializing Garnet server. Please see log messages above for more details.
   at Garnet.GarnetServer..ctor(String[] commandLineArgs, ILoggerFactory loggerFactory, Boolean cleanupDir, IAuthenticationSettings authenticationSettingsOverride)
   at GarnetStart.Program.Main(String[] args) in C:\SEA\SmallProjects\Garnet\GarnetStart\GarnetStart\Program.cs:line 10
   at GarnetStart.Program.<Main>(String[] args) 

We believe this issue, whatever it is, might be what is not allowing us to feed it our garnet.conf file via the option when running as service - but it may not, it's really hard to tell!

### Steps to reproduce the bug

Create console .net8.0 project

add Microsoft.Garnett (any recent version, 1.0.39 for example)

change main method:
```
 static async Task Main(string[] args)
 {
     using var server = new Garnet.GarnetServer(args);
     server.Start();
     await Task.Delay(Timeout.Infinite);
 }
````

Start project (fine)
Start from command line (fine)
Start from command line with --help option (display help, then crash)

### Expected behavior

show help info, then quit gracefully, or keep running.

### Screenshots

07::25::05 info: ArgParser[0] Configuration import from embedded resource succeeded. Path: defaults.conf.
Unhandled exception. Garnet.common.GarnetException: Encountered an error when initializing Garnet server. Please see log messages above for more details.
   at Garnet.GarnetServer..ctor(String[] commandLineArgs, ILoggerFactory loggerFactory, Boolean cleanupDir, IAuthenticationSettings authenticationSettingsOverride)
   at GarnetStart.Program.Main(String[] args) in C:\SEA\SmallProjects\Garnet\GarnetStart\GarnetStart\Program.cs:line 10
   at GarnetStart.Program.<Main>(String[] args)

### Release version

1.0.39

### IDE

Visual Studio 2022
command line
Windows service

### OS version

Windows 10
Windows server 20xx

### Additional context

My end game is to get it up as a BackgroundService-ified version of the service as a windows service a la:
> sc config "Famis Web PubSub" binPath="D:\AppsSvc\FamisPubSubService\FamisPubSubService.exe --config-import-path D:\AppsSvc\FamisPubSubService\garnet.conf"

seem to get more or less the same unspecified error in constructor, This does work on command line, so...odd:
> FamisPubSubService.exe --config-import-path D:\AppsSvc\FamisPubSubService\garnet.conf 

I think I'll be able to solve that, once the issue that prevents construction with just the --help option is sorted, and the missing log message shows up.

**Comment by TalZaccai** [comment]
Hi @zachrybaker! Any other issues at start up other than running with --help? Are you able to successfully start with your garnet.conf file?

**Comment by zachrybaker** [comment]
@TalZaccai, prompt work here!
To answer your question, using my garnet.conf file works fine - from command line. But using it when starting as a windows service fails with similar unhelpful error message. But it starts fine as a service when using  --port, so I’m unsure where to go. It does not appear to be permissions for the account running the service.

**Comment by TalZaccai** [comment]
@zachrybaker Can you elaborate on how you're running your service? Are you using ```hosting/Windows/Garnet.worker```?

**Comment by zachrybaker** [comment]
I’m using a windows service, using nearly exactly identical code as the example you just referenced, which I had not seen before.

**Comment by badrishc** [comment]
It's possible you also have a Redis service so the port clashes on startup. Since the original issue is fixed, please feel free to open a new one if you run into an issue when the port is not in use. Thank you
