### ISSUE TITLE
helm upgrade --install garnet oci://ghcr.io/microsoft/helm-charts/garnet is failing with unknown repository

### ISSUE THREAD

**Issue by mloskot** [microsoft/garnet#845]
### Describe the bug

The Helm chart seems to be missing from the GitHub Container Registry, see https://github.com/microsoft/garnet/pull/594#issuecomment-2511731990

### Steps to reproduce the bug

1. Go to https://github.com/microsoft/garnet/blob/55f94e3ea19c9204ed9154db40bf93dfa8d4f7ce/charts/garnet/README.md?plain=1#L21
2. Follow the instruction _"To install the garnet chart (using an OCI-based registry):"_

    ```bash
    $ helm upgrade --install garnet oci://ghcr.io/microsoft/helm-charts/garnet
    Release "garnet" does not exist. Installing it now.
    Error: GET "https://ghcr.io/v2/microsoft/helm-charts/garnet/tags/list": unexpected status code 404: name unknown: repository name not known to registry
    ```

### Expected behavior

Successfully installation.

### Release version

n/a

### IDE

n/a

### OS version

n/a

### Additional context

n/a

**Comment by badrishc** [comment]
cc @babykart

**Comment by babykart** [comment]
Hi @mloskot , the error encountered is normal because the helm chart package will be present when we have tested the corresponding workflow.

**Comment by mloskot** [comment]
@babykart I see. Inspection of the latest run https://github.com/microsoft/garnet/actions/runs/12041710034 of https://github.com/microsoft/garnet/actions/workflows/helm-chart.yml suggested to me it's all green, been already tested and is working now.

**Comment by babykart** [comment]
@mloskot You're right. I think the package generated is in private mode.

**Comment by badrishc** [comment]
How do we make it public?

**Comment by badrishc** [comment]
> [@badrishc](https://github.com/badrishc) As admin/owner https://github.com/users/microsoft/packages/container/helm-charts%2Fgarnet/settings, in the danger zone , 'Change package visibility'. I am not sure about the exact URL.

I dont see any such packages marked as private. i dont think the push is working. the CI action is swallowing the result of the push so we do not know that it failed?

 the URL is github.com/microsoft/garnet (there is no users/microsoft/packages etc)
