### ISSUE TITLE
Plans for an `IDistributedCache` implementation?

### ISSUE THREAD

**Issue by jodydonetti** [microsoft/garnet#85]
Hi all, are you planning on creating an `IDistributedCache` implementation anytime soon?

Since Garnet has been announced as being protocol-compatible with Redis I thought it would've worked right away by using the standard Redis implementation (see [here](https://github.com/dotnet/aspnetcore/blob/main/src/Caching/StackExchangeRedis/src/RedisCache.cs)), but after actually playing with it I discovered that Garnet does not currently [support LUA scripting](https://microsoft.github.io/garnet/docs/welcome/compatibility):

> 3. Garnet does not support Lua scripting. We have an experimental version, but it was noted to be too slow for realistic use so we have not added it to the project.

LUA scripting is what has been used in the aforementioned impl (see [here](https://github.com/dotnet/aspnetcore/blob/ec293ee75c0c022370951a459b188fa81ec8b7c3/src/Caching/StackExchangeRedis/src/RedisCache.cs#L206)) and therefore without it it's not possible to use Garnet this way.

Having a working impl of `IDistributedCache` for Garnet would drive the adoption a lot, since that is the standard way of using a distributed cache in .NET.

Also, that would unlock other great possibilities like being able to use Garnet in projects that use `IDistributedCache` as a _"lingua franca"_, like [FusionCache](https://github.com/ZiggyCreatures/FusionCache) (mine) which is compatible with any impl of such interface ([here](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/CacheLevels.md) for more).

All in all I think that, if the effort for such impl is not huge, that is something that you should consider to skyrocket the usage.

Thoughts?

ps: maybe @mgravell can give us some hints about such approach? Are there any hidden pitfalls that should be looked at?

**Comment by mgravell** [comment]
I've created a ticket "over there ^^^" - can someone confirm whether Garnet has `MULTI`/`EXEC` support? this may influence any changes there

**Comment by PaulusParssinen** [comment]
>... can someone confirm whether Garnet has `MULTI`/`EXEC` support? this may influence any changes there

Quickly looking at the code: yes, it support `MULTI`/`EXEC`.

**Comment by badrishc** [comment]
More info here: https://microsoft.github.io/garnet/docs/extensions/transactions

**Comment by mgravell** [comment]
I ended up just switching it to pipeline (no `multi`/`exec`) - https://github.com/dotnet/aspnetcore/pull/54689

**Comment by jodydonetti** [comment]
My 2 cents on the overall approach: if by slightly changing the standard Redis impl to avoid using LUA scripts leads to better perf and to be compatible with Garnet, "this is the way".

On top of that, if (and only if) it makes sense to better use specific features of Garnet and get even more perf (and maybe also add some extra features on the concrete impl?) then a Garnet-specific impl of `IDistributedCache` may be created.

Users can then either:
- pick the Garnet-specific one if they want absolutely maximum performance (or the potential extra features)
- pick the standard Redis one if they prefer to use a generic Redis client to switch between Redis and Garnet for whatever reason (local vs tests vs prod?)

**Comment by tfranzon** [comment]
@mgravell 
We are using .NET Framework 4.8 and IDistributedCache and gets the "ERR unknown command". Is there any plans to fix this for 4.8 too?

**Comment by mgravell** [comment]
Already done in c; should work from preview4 onwards, and yes that includes backport to older TFMs - we target ".NET current" (so: .NET 9 in preview 4), net462 and ns2.0

**Comment by Meir017** [comment]
Related to #550

**Comment by badrishc** [comment]
Sounds like this is already done, so closing.
