### ISSUE TITLE
Garnet should fail more obviously if   --config-import-path import fails

### ISSUE THREAD

**Issue by benh57** [microsoft/garnet#859]
### Feature request type

Error handling

### Is your feature request related to a problem? Please describe

1, Launch garnet with : garnetserver.exe --config-import-path <invalid.json>

2. Result -> no error or logs presented

### Describe the solution you'd like

I'd suggest setting exitGracefully = false here in ServerSettingsManager.cs.
This seems to do what i want and logs a bunch of text with the JSON error it hit. Is this a solution you'd accept? If so i can put in a PR.

```

`            // If config import file present - import options from file
            if (cmdLineOptions.ConfigImportPath != null)
            {
                importSuccessful = TryImportServerOptions(
                    cmdLineOptions.ConfigImportPath,
                    cmdLineOptions.ConfigImportFormat, initOptions, logger,
                    cmdLineOptions.UseAzureStorageForConfigImport.GetValueOrDefault() ? FileLocationType.AzureStorage : FileLocationType.Local,
                    cmdLineOptions.AzureStorageConnectionString);

                if (!importSuccessful)
                {
// BH change -- dont exit gracefully if config wasn't imported
                    exitGracefully = false;
                    logger?.LogWarning(@"Config Import of options from : {ConfigImportPath} was not successful.", cmdLineOptions.ConfigImportPath);
                    return false;
                }
            }`
```

**Comment by vazois** [comment]
Yes this seems acceptable. Please create PR.

PS: What version of Garnet are you using? The parameter should be --config-import-path.

**Comment by benh57** [comment]
Great. Looks like that was just a typo in my issue, i'm using --config-import-path.

**Comment by badrishc** [comment]
@benh57, would you be able to submit a PR for this?

**Comment by benh57** [comment]
> [@benh57](https://github.com/benh57), would you be able to submit a PR for this?

Will do so now!
