### ISSUE TITLE
Garnet fails to import config if the config file is read only

### ISSUE THREAD

**Issue by benh57** [microsoft/garnet#861]
### Describe the bug

Garnet fails to import json config if the json file is read only.  Reproduced on Win11

### Steps to reproduce the bug

1. Set a json file to read-only
2. Run GarnetServer.exe --config-import-path  (path to readonly json file)

RESULT: config json fails to parse

If the file is set writable, garnet works fine.

### Expected behavior

Should parse a read only file just fine, it's only reading it. 

### OS version

Windows 11

**Comment by vazois** [comment]
Can you please check the attached PR and let me know if you are still experiencing the issue?

**Comment by benh57** [comment]
Looks like that fixes it! thanks!
