### ISSUE TITLE
Garnet does not call IsAuthenticated for data requests

### ISSUE THREAD

**Issue by Xizt** [microsoft/garnet#865]
### Describe the bug

Garnet in `IGarnetAuthenticator` has exposed 
`bool IsAuthenticated { get; }`

Within GarnetAadAuthenticator, we have following which basically validates that the request is within the validity timeframe of the initial connection setup auth process.

```
        public bool IsAuthenticated => IsAuthorized();

        private bool IsAuthorized()
        {
            var now = DateTime.UtcNow;
            return _authorized && now >= _validFrom && now <= _validateTo;
        }
```

The expected behavior is that for all requests, this check is performed and the request is allowed/denied. But this check happens only for ADMIN commands and not for DATA commands. That means once a connection is authenticated initially, it's valid forever until broken even if the initial setup token is expired.

### Steps to reproduce the bug

1. Run garnet instance locally.
2. Run redis-cli/memurai-cli and authenticate the connection. 
3. Setup a breakpoint within any implementation of IGarnetAuthenticator isAuthenticated method.
4. Do GET/SET call.

**Comment by badrishc** [comment]
Could you submit a PR , the fix should be minor. Thanks!
