### ISSUE TITLE
when browsing db, report critical exception

### ISSUE THREAD

**Issue by gettf** [microsoft/garnet#878]
### Describe the bug

build release with .net9, using redis insight browsing keys(about 400k, data size 9G), server output exception:

crit: Session[0] [127.0.0.1:50364] [01FA0ABC] ProcessMessages threw a GarnetException: Garnet.common.GarnetException: Failed to write to response buffer    at Garnet.common.GarnetException.Throw(String message, LogLevel logLevel) in C:\garnet\libs\common\GarnetException.cs:line 57    at Garnet.server.RespServerSession.WriteOutputForScan(Int64 cursorValue, List`1 keys, Byte*& curr, Byte* end) in C:\garnet\libs\server\Resp\ArrayCommands.cs:line 435    at Garnet.server.RespServerSession.NetworkSCAN[TGarnetApi](TGarnetApi& storageApi) in C:\garnet\libs\server\Resp\ArrayCommands.cs:line 382    at Garnet.server.RespServerSession.ProcessOtherCommands[TGarnetApi](RespCommand command, TGarnetApi& storageApi) in C:\garnet\libs\server\Resp\RespServerSession.cs:line 700    at Garnet.server.RespServerSession.ProcessArrayCommands[TGarnetApi](RespCommand cmd, TGarnetApi& storageApi) in C:\garnet\libs\server\Resp\RespServerSession.cs:line 570    at Garnet.server.RespServerSession.ProcessMessages() in C:\garnet\libs\server\Resp\RespServerSession.cs:line 437    at Garnet.server.RespServerSession.TryConsumeMessages(Byte* reqBuffer, Int32 bytesReceived) in C:\garnet\libs\server\Resp\RespServerSession.cs:line 312

### Steps to reproduce the bug

build release with .net9, using redis insight browsing keys(about 400k, data size 9G), server output exception:

### IDE

Visual Studio 2022

### OS version

Windows 11 26100

**Comment by Vijay-Nirmal** [comment]
Is it only happening with that specific data set? Is it possible for you to find the exact key that causes this issue?

**Comment by badrishc** [comment]
Was the specific key or value extremely large, what is the max size of keys and values.
