### ISSUE TITLE
Any plan to support Redis Sentinel?

### ISSUE THREAD

**Issue by Wennn** [microsoft/garnet#91]
I am wondering if there is any plan to support Redis Sentinel mode? Or are there any guidance on how to make Redis Sentinel client work with Garnet seamlessly?
Thanks

**Comment by vazois** [comment]
We don't have any plans to support Redis Sentinel, at least yet. Regarding to what needs to be done, we have to come up with a list of commands that are necessary for sentinel nodes to control a Garnet instance. Right now, we support some of those commands (e.g. REPLICAOF, FAILOVER) but mostly in the context of cluster-mode (i.e. they are disabled if cluster is not enabled).
Another item needed is to make replication available in standalone Garnet. Currently, it only works with cluster.
Any contributions related to the above is strongly encouraged.
